BEGIN;

CREATE SCHEMA IF NOT EXISTS steel;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

SET search_path = steel, public;

REVOKE ALL ON SCHEMA steel FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

CREATE OR REPLACE FUNCTION steel.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS steel.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  erp_customer_code TEXT,
  display_name TEXT NOT NULL,
  legal_name TEXT,
  tax_id TEXT,
  customer_tier TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  notes TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS erp_customer_code TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS legal_name TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS customer_tier TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS source_refs JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.customers DROP COLUMN IF EXISTS import_log_id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'steel'
      AND table_name = 'customers'
      AND column_name = 'customer_tier_id'
  ) THEN
    UPDATE steel.customers
    SET customer_tier = CASE UPPER(customer_tier_id::text)
      WHEN '1' THEN 'A'
      WHEN '2' THEN 'B'
      WHEN '3' THEN 'C'
      WHEN '4' THEN 'F'
      WHEN 'A' THEN 'A'
      WHEN 'B' THEN 'B'
      WHEN 'C' THEN 'C'
      WHEN 'F' THEN 'F'
      ELSE customer_tier
    END
    WHERE customer_tier IS NULL;

    ALTER TABLE steel.customers DROP COLUMN customer_tier_id;
  END IF;
END $$;

UPDATE steel.customers SET status = 'archived' WHERE status = 'deleted';

ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_status_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_tier_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_metadata_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_source_refs_check;
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_status_check
  CHECK (status IN ('active', 'inactive', 'archived'));
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_tier_check
  CHECK (customer_tier IS NULL OR customer_tier IN ('A', 'B', 'C', 'F'));
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_metadata_check
  CHECK (jsonb_typeof(metadata) = 'object');
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');

COMMENT ON COLUMN steel.customers.customer_tier IS
  'Uppercase product price tier code A/B/C/F. Quote calculation defaults to B when tier is unknown.';

DROP INDEX IF EXISTS steel.customers_erp_customer_code_unique_idx;
CREATE UNIQUE INDEX IF NOT EXISTS customers_erp_customer_code_unique_idx
ON steel.customers (erp_customer_code)
WHERE erp_customer_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS customers_display_name_trgm_idx
ON steel.customers USING GIN (display_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS customers_legal_name_trgm_idx
ON steel.customers USING GIN (legal_name gin_trgm_ops)
WHERE legal_name IS NOT NULL;

CREATE INDEX IF NOT EXISTS customers_tax_id_trgm_idx
ON steel.customers USING GIN (tax_id gin_trgm_ops)
WHERE tax_id IS NOT NULL;

DROP TRIGGER IF EXISTS set_customers_updated_at ON steel.customers;
CREATE TRIGGER set_customers_updated_at
BEFORE UPDATE ON steel.customers
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

CREATE TABLE IF NOT EXISTS steel.formula_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  version_seq INTEGER NOT NULL,
  display_name TEXT,
  source_expression TEXT,
  formula_body JSONB NOT NULL DEFAULT '{}'::jsonb,
  compiled_formula JSONB,
  allowed_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS version_seq INTEGER;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS source_expression TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS formula_body JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS compiled_formula JSONB;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS allowed_variables JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS review_state TEXT NOT NULL DEFAULT 'reviewed';
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS source_refs JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_code_version_unique;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_review_state_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_formula_body_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_allowed_variables_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_source_refs_check;
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_code_version_unique UNIQUE (code, version_seq);
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_review_state_check
  CHECK (review_state IN ('draft', 'needs_review', 'reviewed', 'rejected'));
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_formula_body_check
  CHECK (jsonb_typeof(formula_body) = 'object');
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_allowed_variables_check
  CHECK (jsonb_typeof(allowed_variables) = 'array');
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');

DROP TRIGGER IF EXISTS set_formula_versions_updated_at ON steel.formula_versions;
CREATE TRIGGER set_formula_versions_updated_at
BEFORE UPDATE ON steel.formula_versions
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

DROP TABLE IF EXISTS steel.price_rule_conditions CASCADE;
DROP TABLE IF EXISTS steel.price_history CASCADE;
DROP TABLE IF EXISTS steel.price_items CASCADE;
DROP TABLE IF EXISTS steel.price_categories CASCADE;
DROP TABLE IF EXISTS steel.product_name_aliases CASCADE;
DROP TABLE IF EXISTS steel.customer_aliases CASCADE;
DROP TABLE IF EXISTS steel.customer_tiers CASCADE;
DROP TABLE IF EXISTS steel.agent_rules CASCADE;
DROP TABLE IF EXISTS steel.quote_rules CASCADE;
DROP TABLE IF EXISTS steel.customer_rules CASCADE;
DROP TABLE IF EXISTS steel.catalog_family_rules CASCADE;
DROP TABLE IF EXISTS steel.material_rules CASCADE;
DROP TABLE IF EXISTS steel.instruction_packets CASCADE;
DROP TABLE IF EXISTS steel.quote_defaults CASCADE;
DROP TABLE IF EXISTS steel.lesson_memory_entries CASCADE;
DROP TABLE IF EXISTS steel.source_chunks CASCADE;
DROP TABLE IF EXISTS steel.source_embeddings CASCADE;
DROP TABLE IF EXISTS steel.weight_specs CASCADE;
DROP TABLE IF EXISTS steel.orders CASCADE;
DROP TABLE IF EXISTS steel.order_items CASCADE;
DROP TABLE IF EXISTS steel.import_rule_notes CASCADE;
DROP TABLE IF EXISTS steel.catalog_families CASCADE;

CREATE TABLE IF NOT EXISTS steel.prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_kind TEXT NOT NULL,
  source_dataset TEXT NOT NULL,
  source_row_key TEXT NOT NULL,
  erp_item_code TEXT,
  product_name TEXT NOT NULL,
  spec_key TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  material TEXT,
  source_category_label TEXT,
  source_subcategory_label TEXT,
  source_material_label TEXT,
  source_thickness TEXT,
  source_spec TEXT,
  unit TEXT NOT NULL DEFAULT 'piece',
  currency TEXT NOT NULL DEFAULT 'TWD',
  unit_price_a NUMERIC(14, 4),
  unit_price_b NUMERIC(14, 4),
  unit_price_c NUMERIC(14, 4),
  unit_price_f NUMERIC(14, 4),
  product_price_unit_weight NUMERIC(14, 5),
  product_price_unit_weight_unit TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  value_state TEXT NOT NULL DEFAULT 'confirmed',
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_kind_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_category_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_material_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_value_state_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_review_state_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_unit_prices_nonnegative_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_confirmed_has_price_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_unknown_has_no_price_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_metadata_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_source_refs_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_source_row_unique;
ALTER TABLE steel.prices
  ADD COLUMN IF NOT EXISTS subcategory TEXT,
  ADD COLUMN IF NOT EXISTS source_subcategory_label TEXT;
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_kind_check
  CHECK (price_kind IN ('product', 'cutting', 'hole'));
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_category_check
  CHECK (category IN (
    'C型鋼', 'H型鋼', '鐵板/鋼板', '圓鐵/圓鋼', '角鐵/角鋼',
    '孔', '平鐵/扁鐵', '槽鐵', '工字鐵/I字鐵', '方鋼/方鐵',
    '圓管/鋼管', '方管', '扁方管', '樓層板', '浪板/收邊',
    '網材', '門窗/捲門/配件', '五金/零件/耗材', '折工',
    '切工/切割', '非鋼材/其他材料', '鐵軌', 'T型鋼', '加工'
  ));
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_material_check
  CHECK (
    material IS NULL OR material IN (
      'OT 黑鐵', 'ST 白鐵', '2B 白鐵霧面', 'BA 白鐵亮面',
      'HL 白鐵沙面', 'No1 白鐵', '錏/鍍鋅', '錏', '鋁鋅',
      '彩色/烤漆', '中碳鋼', '鋁', '非鋼材', '塑膠',
      '玻璃', '無', '待確認'
    )
  );
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_value_state_check
  CHECK (value_state IN ('unknown', 'confirmed', 'true_zero', 'estimate'));
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_review_state_check
  CHECK (review_state IN ('draft', 'needs_review', 'reviewed', 'rejected'));
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_unit_prices_nonnegative_check CHECK (
    (unit_price_a IS NULL OR unit_price_a >= 0)
    AND (unit_price_b IS NULL OR unit_price_b >= 0)
    AND (unit_price_c IS NULL OR unit_price_c >= 0)
    AND (unit_price_f IS NULL OR unit_price_f >= 0)
  );
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_confirmed_has_price_check CHECK (
    value_state = 'unknown'
    OR unit_price_a IS NOT NULL
    OR unit_price_b IS NOT NULL
    OR unit_price_c IS NOT NULL
    OR unit_price_f IS NOT NULL
  );
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_unknown_has_no_price_check CHECK (
    value_state <> 'unknown'
    OR (
      unit_price_a IS NULL
      AND unit_price_b IS NULL
      AND unit_price_c IS NULL
      AND unit_price_f IS NULL
    )
  );
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_metadata_check
  CHECK (jsonb_typeof(metadata) = 'object');
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_source_row_unique UNIQUE (source_dataset, source_row_key);

CREATE INDEX IF NOT EXISTS prices_kind_category_idx
ON steel.prices (price_kind, category);
CREATE INDEX IF NOT EXISTS prices_kind_category_material_idx
ON steel.prices (price_kind, category, material);
CREATE INDEX IF NOT EXISTS prices_kind_category_subcategory_idx
ON steel.prices (price_kind, category, subcategory);
CREATE INDEX IF NOT EXISTS prices_review_active_idx
ON steel.prices (review_state, active);
CREATE INDEX IF NOT EXISTS prices_spec_key_trgm_idx
ON steel.prices USING GIN (spec_key gin_trgm_ops);
CREATE INDEX IF NOT EXISTS prices_product_name_trgm_idx
ON steel.prices USING GIN (product_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS prices_subcategory_trgm_idx
ON steel.prices USING GIN (subcategory gin_trgm_ops)
WHERE subcategory IS NOT NULL;
CREATE INDEX IF NOT EXISTS prices_source_subcategory_trgm_idx
ON steel.prices USING GIN (source_subcategory_label gin_trgm_ops)
WHERE source_subcategory_label IS NOT NULL;
CREATE INDEX IF NOT EXISTS prices_source_thickness_trgm_idx
ON steel.prices USING GIN (source_thickness gin_trgm_ops)
WHERE source_thickness IS NOT NULL;
CREATE INDEX IF NOT EXISTS prices_source_spec_trgm_idx
ON steel.prices USING GIN (source_spec gin_trgm_ops)
WHERE source_spec IS NOT NULL;

COMMENT ON TABLE steel.prices IS
'Unified Steel price rows. Tier prices are stored only in unit_price_a, unit_price_b, unit_price_c, and unit_price_f; source 比率A-F columns are intentionally ignored and not persisted.';
COMMENT ON COLUMN steel.prices.subcategory IS
'Normalized price subcategory, primarily for cutting tables such as H型鋼, 工字鐵/H型鋼, 管, 角鐵, 槽鐵, 平鐵/扁鐵.';
COMMENT ON COLUMN steel.prices.source_subcategory_label IS
'Source worksheet 次類別 label after reviewed cleanup.';

DROP TRIGGER IF EXISTS set_prices_updated_at ON steel.prices;
CREATE TRIGGER set_prices_updated_at
BEFORE UPDATE ON steel.prices
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

CREATE TABLE IF NOT EXISTS steel.rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  rule_kind TEXT NOT NULL,
  title TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'zh-TW',
  rule_sections TEXT[] NOT NULL DEFAULT '{}'::text[],
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  prompt TEXT NOT NULL,
  tool_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  priority INTEGER NOT NULL DEFAULT 100,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_kind_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_review_state_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_selectors_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_tool_policy_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_output_policy_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_source_refs_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_slug_version_unique;
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_kind_check
  CHECK (rule_kind IN ('agent', 'output', 'steel', 'other'));
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_review_state_check
  CHECK (review_state IN ('draft', 'needs_review', 'reviewed', 'rejected'));
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_selectors_check
  CHECK (jsonb_typeof(selectors) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_tool_policy_check
  CHECK (jsonb_typeof(tool_policy) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_output_policy_check
  CHECK (jsonb_typeof(output_policy) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_slug_version_unique UNIQUE (slug, version);

CREATE INDEX IF NOT EXISTS rules_kind_active_review_priority_idx
ON steel.rules (rule_kind, active, review_state, priority);
CREATE INDEX IF NOT EXISTS rules_prompt_trgm_idx
ON steel.rules USING GIN (prompt gin_trgm_ops);
CREATE INDEX IF NOT EXISTS rules_title_trgm_idx
ON steel.rules USING GIN (title gin_trgm_ops);

DROP TRIGGER IF EXISTS set_rules_updated_at ON steel.rules;
CREATE TRIGGER set_rules_updated_at
BEFORE UPDATE ON steel.rules
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

COMMIT;
