BEGIN;

CREATE SCHEMA IF NOT EXISTS steel;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

SET search_path = steel, public;

REVOKE ALL ON SCHEMA steel FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA steel REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

CREATE OR REPLACE FUNCTION steel.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS steel.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  erp_customer_code TEXT,
  display_name TEXT NOT NULL,
  legal_name TEXT,
  tax_id TEXT,
  customer_tier TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  notes TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS erp_customer_code TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS legal_name TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS customer_tier TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS source_refs JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.customers DROP COLUMN IF EXISTS import_log_id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'steel'
      AND table_name = 'customers'
      AND column_name = 'customer_tier_id'
  ) THEN
    UPDATE steel.customers
    SET customer_tier = CASE UPPER(customer_tier_id::text)
      WHEN '1' THEN 'A'
      WHEN '2' THEN 'B'
      WHEN '3' THEN 'C'
      WHEN '4' THEN 'F'
      WHEN 'A' THEN 'A'
      WHEN 'B' THEN 'B'
      WHEN 'C' THEN 'C'
      WHEN 'F' THEN 'F'
      ELSE customer_tier
    END
    WHERE customer_tier IS NULL;

    ALTER TABLE steel.customers DROP COLUMN customer_tier_id;
  END IF;
END $$;

UPDATE steel.customers SET status = 'archived' WHERE status = 'deleted';

ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_status_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_tier_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_metadata_check;
ALTER TABLE steel.customers DROP CONSTRAINT IF EXISTS customers_source_refs_check;
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_status_check
  CHECK (status IN ('active', 'inactive', 'archived'));
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_tier_check
  CHECK (customer_tier IS NULL OR customer_tier IN ('A', 'B', 'C', 'F'));
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_metadata_check
  CHECK (jsonb_typeof(metadata) = 'object');
ALTER TABLE steel.customers
  ADD CONSTRAINT customers_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');

COMMENT ON COLUMN steel.customers.customer_tier IS
  'Uppercase product price tier code A/B/C/F. Quote calculation defaults to B when tier is unknown.';

DROP INDEX IF EXISTS steel.customers_erp_customer_code_unique_idx;
CREATE UNIQUE INDEX IF NOT EXISTS customers_erp_customer_code_unique_idx
ON steel.customers (erp_customer_code)
WHERE erp_customer_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS customers_display_name_trgm_idx
ON steel.customers USING GIN (display_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS customers_legal_name_trgm_idx
ON steel.customers USING GIN (legal_name gin_trgm_ops)
WHERE legal_name IS NOT NULL;

CREATE INDEX IF NOT EXISTS customers_tax_id_trgm_idx
ON steel.customers USING GIN (tax_id gin_trgm_ops)
WHERE tax_id IS NOT NULL;

DROP TRIGGER IF EXISTS set_customers_updated_at ON steel.customers;
CREATE TRIGGER set_customers_updated_at
BEFORE UPDATE ON steel.customers
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

CREATE TABLE IF NOT EXISTS steel.formula_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  version_seq INTEGER NOT NULL,
  display_name TEXT,
  source_expression TEXT,
  formula_body JSONB NOT NULL DEFAULT '{}'::jsonb,
  compiled_formula JSONB,
  allowed_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS version_seq INTEGER;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS source_expression TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS formula_body JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS compiled_formula JSONB;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS allowed_variables JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS review_state TEXT NOT NULL DEFAULT 'reviewed';
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS source_refs JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE steel.formula_versions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_code_version_unique;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_review_state_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_formula_body_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_allowed_variables_check;
ALTER TABLE steel.formula_versions DROP CONSTRAINT IF EXISTS formula_versions_source_refs_check;
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_code_version_unique UNIQUE (code, version_seq);
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_review_state_check
  CHECK (review_state IN ('draft', 'needs_review', 'reviewed', 'rejected'));
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_formula_body_check
  CHECK (jsonb_typeof(formula_body) = 'object');
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_allowed_variables_check
  CHECK (jsonb_typeof(allowed_variables) = 'array');
ALTER TABLE steel.formula_versions
  ADD CONSTRAINT formula_versions_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');

DROP TRIGGER IF EXISTS set_formula_versions_updated_at ON steel.formula_versions;
CREATE TRIGGER set_formula_versions_updated_at
BEFORE UPDATE ON steel.formula_versions
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

DROP TABLE IF EXISTS steel.price_rule_conditions CASCADE;
DROP TABLE IF EXISTS steel.price_history CASCADE;
DROP TABLE IF EXISTS steel.price_items CASCADE;
DROP TABLE IF EXISTS steel.price_categories CASCADE;
DROP TABLE IF EXISTS steel.product_name_aliases CASCADE;
DROP TABLE IF EXISTS steel.customer_aliases CASCADE;
DROP TABLE IF EXISTS steel.customer_tiers CASCADE;
DROP TABLE IF EXISTS steel.agent_rules CASCADE;
DROP TABLE IF EXISTS steel.quote_rules CASCADE;
DROP TABLE IF EXISTS steel.customer_rules CASCADE;
DROP TABLE IF EXISTS steel.catalog_family_rules CASCADE;
DROP TABLE IF EXISTS steel.material_rules CASCADE;
DROP TABLE IF EXISTS steel.instruction_packets CASCADE;
DROP TABLE IF EXISTS steel.quote_defaults CASCADE;
DROP TABLE IF EXISTS steel.lesson_memory_entries CASCADE;
DROP TABLE IF EXISTS steel.source_chunks CASCADE;
DROP TABLE IF EXISTS steel.source_embeddings CASCADE;
DROP TABLE IF EXISTS steel.weight_specs CASCADE;
DROP TABLE IF EXISTS steel.orders CASCADE;
DROP TABLE IF EXISTS steel.order_items CASCADE;
DROP TABLE IF EXISTS steel.import_rule_notes CASCADE;
DROP TABLE IF EXISTS steel.catalog_families CASCADE;

CREATE TABLE IF NOT EXISTS steel.prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  erp_item_code TEXT NOT NULL,
  formula_code TEXT,
  product_name TEXT,
  category TEXT NOT NULL,
  subcategory TEXT,
  processing_method TEXT,
  processing_shape TEXT,
  material TEXT,
  unit TEXT,
  value_state TEXT NOT NULL,
  unit_price_base NUMERIC(18, 4),
  unit_price_a NUMERIC(18, 4),
  unit_price_b NUMERIC(18, 4),
  unit_price_c NUMERIC(18, 4),
  unit_price_d NUMERIC(18, 4),
  unit_price_e NUMERIC(18, 4),
  unit_price_f NUMERIC(18, 4),
  price_ratio_a NUMERIC(18, 4),
  price_ratio_b NUMERIC(18, 4),
  price_ratio_c NUMERIC(18, 4),
  price_ratio_d NUMERIC(18, 4),
  price_ratio_e NUMERIC(18, 4),
  price_ratio_f NUMERIC(18, 4),
  unit_weight_value NUMERIC(18, 6),
  unit_weight_basis TEXT,
  density NUMERIC(18, 6),
  thickness_min_mm NUMERIC(18, 6),
  thickness_max_mm NUMERIC(18, 6),
  width_mm NUMERIC(18, 6),
  height_mm NUMERIC(18, 6),
  length_mm NUMERIC(18, 6),
  outer_diameter_mm NUMERIC(18, 6),
  nominal_inch TEXT,
  web_mm NUMERIC(18, 6),
  flange_mm NUMERIC(18, 6),
  lip_mm NUMERIC(18, 6),
  sheet_width_mm NUMERIC(18, 6),
  sheet_length_mm NUMERIC(18, 6),
  spec_sort_key TEXT,
  cost_basis TEXT NOT NULL,
  spec_key TEXT NOT NULL
);

ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_kind_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_category_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_material_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_value_state_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_review_state_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_unit_prices_nonnegative_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_confirmed_has_price_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_unknown_has_no_price_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_metadata_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_source_refs_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_source_row_unique;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_erp_item_code_unique;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_source_dataset_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_currency_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_cost_basis_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_numeric_values_nonnegative_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_value_state_invariants_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_subcategory_not_blank_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_thickness_range_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_processing_method_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_processing_shape_check;
ALTER TABLE steel.prices DROP CONSTRAINT IF EXISTS prices_processing_attributes_category_check;
DROP INDEX IF EXISTS steel.prices_review_active_idx;
ALTER TABLE steel.prices DROP COLUMN IF EXISTS review_state;
ALTER TABLE steel.prices
  ADD CONSTRAINT prices_erp_item_code_unique UNIQUE (erp_item_code),
  ADD CONSTRAINT prices_category_check
  CHECK (category IN (
    'C型鋼', 'H型鋼', 'I型鋼/工字鐵', 'T型鋼', '鐵板', '平鐵', '角鐵',
    '圓條', '鋼筋', '圓管', '方鐵', '方管', '扁方管', '網', '格板/隔板', '板/浪板',
    '鐵軌', '槽鐵', '捲門/伸縮門', '門窗/門板', '五金/配件', '加工/孔',
    '加工/切工', '加工/倒角', '加工/開槽', '加工/折工', '加工/焊接',
    '加工/其他', '其他'
  )),
  ADD CONSTRAINT prices_value_state_check
  CHECK (value_state IN ('confirmed', 'ratio_only', 'no_price')),
  ADD CONSTRAINT prices_cost_basis_check
  CHECK (cost_basis IN ('1.總數', '2.數量')),
  ADD CONSTRAINT prices_thickness_range_check CHECK (
    (thickness_min_mm IS NULL AND thickness_max_mm IS NULL)
    OR (
      thickness_min_mm IS NOT NULL
      AND thickness_max_mm IS NOT NULL
      AND thickness_min_mm > 0
      AND thickness_max_mm > 0
      AND thickness_min_mm <= thickness_max_mm
    )
  ),
  ADD CONSTRAINT prices_processing_method_check CHECK (
    processing_method IS NULL
    OR processing_method IN ('剪床', '雷射', '鋸床', '水刀', '火', '沖床', '鑽床')
  ),
  ADD CONSTRAINT prices_processing_shape_check CHECK (
    processing_shape IS NULL
    OR processing_shape IN ('外形切割', '直線切割', '圓孔', '方孔', '菱形孔', '長孔', '橢圓孔', '其他')
  ),
  ADD CONSTRAINT prices_processing_attributes_category_check CHECK (
    category LIKE '加工/%'
    OR (processing_method IS NULL AND processing_shape IS NULL)
  ),
  ADD CONSTRAINT prices_numeric_values_nonnegative_check CHECK (
    (unit_price_base IS NULL OR unit_price_base >= 0)
    AND (unit_price_a IS NULL OR unit_price_a >= 0)
    AND (unit_price_b IS NULL OR unit_price_b >= 0)
    AND (unit_price_c IS NULL OR unit_price_c >= 0)
    AND (unit_price_d IS NULL OR unit_price_d >= 0)
    AND (unit_price_e IS NULL OR unit_price_e >= 0)
    AND (unit_price_f IS NULL OR unit_price_f >= 0)
    AND (price_ratio_a IS NULL OR price_ratio_a >= 0)
    AND (price_ratio_b IS NULL OR price_ratio_b >= 0)
    AND (price_ratio_c IS NULL OR price_ratio_c >= 0)
    AND (price_ratio_d IS NULL OR price_ratio_d >= 0)
    AND (price_ratio_e IS NULL OR price_ratio_e >= 0)
    AND (price_ratio_f IS NULL OR price_ratio_f >= 0)
    AND (unit_weight_value IS NULL OR unit_weight_value >= 0)
    AND (density IS NULL OR density >= 0)
    AND (width_mm IS NULL OR width_mm >= 0)
    AND (height_mm IS NULL OR height_mm >= 0)
    AND (length_mm IS NULL OR length_mm >= 0)
    AND (outer_diameter_mm IS NULL OR outer_diameter_mm >= 0)
    AND (web_mm IS NULL OR web_mm >= 0)
    AND (flange_mm IS NULL OR flange_mm >= 0)
    AND (lip_mm IS NULL OR lip_mm >= 0)
    AND (sheet_width_mm IS NULL OR sheet_width_mm >= 0)
    AND (sheet_length_mm IS NULL OR sheet_length_mm >= 0)
  ),
  ADD CONSTRAINT prices_value_state_invariants_check CHECK (
    (
      value_state = 'confirmed'
      AND (
        unit_price_base IS NOT NULL
        OR unit_price_a IS NOT NULL
        OR unit_price_b IS NOT NULL
        OR unit_price_c IS NOT NULL
        OR unit_price_d IS NOT NULL
        OR unit_price_e IS NOT NULL
        OR unit_price_f IS NOT NULL
      )
    )
    OR (
      value_state = 'ratio_only'
      AND unit_price_base IS NULL
      AND unit_price_a IS NULL
      AND unit_price_b IS NULL
      AND unit_price_c IS NULL
      AND unit_price_d IS NULL
      AND unit_price_e IS NULL
      AND unit_price_f IS NULL
      AND (
        price_ratio_a IS NOT NULL
        OR price_ratio_b IS NOT NULL
        OR price_ratio_c IS NOT NULL
        OR price_ratio_d IS NOT NULL
        OR price_ratio_e IS NOT NULL
        OR price_ratio_f IS NOT NULL
      )
    )
    OR (
      value_state = 'no_price'
      AND unit_price_base IS NULL
      AND unit_price_a IS NULL
      AND unit_price_b IS NULL
      AND unit_price_c IS NULL
      AND unit_price_d IS NULL
      AND unit_price_e IS NULL
      AND unit_price_f IS NULL
      AND price_ratio_a IS NULL
      AND price_ratio_b IS NULL
      AND price_ratio_c IS NULL
      AND price_ratio_d IS NULL
      AND price_ratio_e IS NULL
      AND price_ratio_f IS NULL
    )
  ),
  ADD CONSTRAINT prices_subcategory_not_blank_check
  CHECK (subcategory IS NULL OR BTRIM(subcategory) <> '');

CREATE INDEX IF NOT EXISTS prices_category_lookup_idx
ON steel.prices (category, subcategory, material, unit);
CREATE INDEX IF NOT EXISTS prices_spec_key_trgm_idx
ON steel.prices USING GIN (spec_key gin_trgm_ops);
CREATE INDEX IF NOT EXISTS prices_product_name_trgm_idx
ON steel.prices USING GIN (product_name gin_trgm_ops)
WHERE product_name IS NOT NULL;
CREATE INDEX IF NOT EXISTS prices_subcategory_trgm_idx
ON steel.prices USING GIN (subcategory gin_trgm_ops)
WHERE subcategory IS NOT NULL;

COMMENT ON TABLE steel.prices IS
'Steel normalized product price v4.4 rows upserted atomically from products_db_ready; erp_item_code is row identity and spec_key is canonical keyword text.';
COMMENT ON COLUMN steel.prices.subcategory IS
'Validated query-facing subcategory; workbook blanks are stored as SQL NULL.';
COMMENT ON COLUMN steel.prices.processing_method IS
'Normalized processing method for machining price lookup.';
COMMENT ON COLUMN steel.prices.processing_shape IS
'Normalized cutting or hole shape for machining price lookup.';

DROP TRIGGER IF EXISTS set_prices_updated_at ON steel.prices;

DROP TABLE IF EXISTS steel.cutting_prices CASCADE;

CREATE TABLE steel.cutting_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cutting_category TEXT NOT NULL,
  item_name TEXT NOT NULL,
  cut_type TEXT NOT NULL,
  spec_text TEXT,
  inch_min NUMERIC(18, 9),
  inch_max NUMERIC(18, 9),
  mm_min NUMERIC(18, 9),
  mm_max NUMERIC(18, 9),
  height_mm NUMERIC(18, 9),
  width_mm NUMERIC(18, 9),
  thickness_mm_values NUMERIC(18, 9)[],
  thickness_mm_min NUMERIC(18, 9),
  thickness_mm_max NUMERIC(18, 9),
  unit TEXT,
  unit_price_a NUMERIC(18, 4),
  unit_price_b NUMERIC(18, 4),
  unit_price_c NUMERIC(18, 4),
  unit_price_f NUMERIC(18, 4),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cutting_prices_cut_type_check
  CHECK (cut_type = '加工/切工'),
  CONSTRAINT cutting_prices_required_text_check
  CHECK (
    BTRIM(cutting_category) <> ''
    AND BTRIM(item_name) <> ''
    AND BTRIM(cut_type) <> ''
  ),
  CONSTRAINT cutting_prices_profile_dimensions_check
  CHECK (
    (
      cutting_category IN ('H型鋼', '工字鐵/H型鋼')
      AND height_mm > 0
      AND width_mm > 0
    )
    OR (
      cutting_category NOT IN ('H型鋼', '工字鐵/H型鋼')
      AND height_mm IS NULL
      AND width_mm IS NULL
    )
  ),
  CONSTRAINT cutting_prices_values_check
  CHECK (
    (unit_price_a IS NULL OR unit_price_a >= 0)
    AND (unit_price_b IS NULL OR unit_price_b >= 0)
    AND (unit_price_c IS NULL OR unit_price_c >= 0)
    AND (unit_price_f IS NULL OR unit_price_f >= 0)
    AND (
      (
        cutting_category IN ('H型鋼', '工字鐵/H型鋼')
        AND inch_min IS NULL AND inch_max IS NULL
        AND mm_min IS NULL AND mm_max IS NULL
      )
      OR (
        cutting_category NOT IN ('H型鋼', '工字鐵/H型鋼')
        AND (
          (
            inch_min IS NULL AND inch_max IS NULL
            AND mm_min IS NOT NULL AND mm_max IS NOT NULL
            AND mm_min > 0 AND mm_max > 0 AND mm_min <= mm_max
          )
          OR (
            inch_min IS NOT NULL AND inch_max IS NOT NULL
            AND mm_min IS NOT NULL AND mm_max IS NOT NULL
            AND inch_min > 0 AND inch_max > 0 AND inch_min <= inch_max
            AND mm_min > 0 AND mm_max > 0 AND mm_min <= mm_max
            AND mm_min = ROUND(inch_min * 25.4, 9)
            AND mm_max = ROUND(inch_max * 25.4, 9)
          )
        )
      )
    )
    AND (
      (
        thickness_mm_values IS NULL
        AND thickness_mm_min IS NULL
        AND thickness_mm_max IS NULL
      )
      OR (
        thickness_mm_values IS NOT NULL
        AND cardinality(thickness_mm_values) > 0
        AND 0 < ALL(thickness_mm_values)
        AND thickness_mm_min IS NULL
        AND thickness_mm_max IS NULL
      )
      OR (
        thickness_mm_values IS NULL
        AND (thickness_mm_min IS NOT NULL OR thickness_mm_max IS NOT NULL)
        AND (thickness_mm_min IS NULL OR thickness_mm_min > 0)
        AND (thickness_mm_max IS NULL OR thickness_mm_max > 0)
        AND (
          thickness_mm_min IS NULL
          OR thickness_mm_max IS NULL
          OR thickness_mm_min <= thickness_mm_max
        )
      )
    )
  ),
  CONSTRAINT cutting_prices_thickness_array_nonnull_check
  CHECK (
    thickness_mm_values IS NULL
    OR array_position(thickness_mm_values, NULL) IS NULL
  ),
  CONSTRAINT cutting_prices_unit_check
  CHECK (
    unit = '刀'
  )
);

CREATE INDEX cutting_prices_category_idx
ON steel.cutting_prices (cutting_category);

COMMENT ON TABLE steel.cutting_prices IS
'Price-only 加工/切工 catalog atomically imported from docs/reference/切工價錢-raw.xlsx.';

COMMENT ON COLUMN steel.cutting_prices.height_mm IS
'H型鋼 or 工字鐵/H型鋼 profile height in millimeters.';

COMMENT ON COLUMN steel.cutting_prices.width_mm IS
'H型鋼 or 工字鐵/H型鋼 profile width in millimeters.';

DROP TRIGGER IF EXISTS set_cutting_prices_updated_at ON steel.cutting_prices;
CREATE TRIGGER set_cutting_prices_updated_at
BEFORE UPDATE ON steel.cutting_prices
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

CREATE TABLE IF NOT EXISTS steel.rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  rule_kind TEXT NOT NULL,
  title TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'zh-TW',
  rule_sections TEXT[] NOT NULL DEFAULT '{}'::text[],
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  prompt TEXT NOT NULL,
  tool_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  priority INTEGER NOT NULL DEFAULT 100,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_kind_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_review_state_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_selectors_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_tool_policy_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_output_policy_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_source_refs_check;
ALTER TABLE steel.rules DROP CONSTRAINT IF EXISTS rules_slug_version_unique;
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_kind_check
  CHECK (rule_kind IN ('agent', 'output', 'steel', 'other'));
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_review_state_check
  CHECK (review_state IN ('draft', 'needs_review', 'reviewed', 'rejected'));
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_selectors_check
  CHECK (jsonb_typeof(selectors) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_tool_policy_check
  CHECK (jsonb_typeof(tool_policy) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_output_policy_check
  CHECK (jsonb_typeof(output_policy) = 'object');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_source_refs_check
  CHECK (jsonb_typeof(source_refs) = 'array');
ALTER TABLE steel.rules
  ADD CONSTRAINT rules_slug_version_unique UNIQUE (slug, version);

CREATE INDEX IF NOT EXISTS rules_kind_active_review_priority_idx
ON steel.rules (rule_kind, active, review_state, priority);
CREATE INDEX IF NOT EXISTS rules_prompt_trgm_idx
ON steel.rules USING GIN (prompt gin_trgm_ops);
CREATE INDEX IF NOT EXISTS rules_title_trgm_idx
ON steel.rules USING GIN (title gin_trgm_ops);

DROP TRIGGER IF EXISTS set_rules_updated_at ON steel.rules;
CREATE TRIGGER set_rules_updated_at
BEFORE UPDATE ON steel.rules
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();

ALTER TABLE steel.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.cutting_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.formula_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.rules DISABLE ROW LEVEL SECURITY;

COMMIT;
