export const priceCategories = Object.freeze([
  '加工/其他',
  '加工/孔',
  '其他',
  '圓鐵',
  '捲門/伸縮門',
  '網',
  '格板/隔板',
  '五金/配件',
  '門窗/門板',
  '鐵板',
  '加工/折工',
  '加工/切工',
  'C型鋼',
  '板/浪板',
  '方鐵',
  'H型鋼',
  'T型鋼',
  '平鐵',
  '角鐵',
  '圓管',
  '鐵軌',
  '槽鐵',
  'I型鋼/工字鐵',
  '方管',
  '扁方管',
  '加工/開槽',
] as const);

export type PriceCategory = (typeof priceCategories)[number];

const registry = Object.freeze({
  '加工/其他': Object.freeze([
    '',
    'C型鋼',
    'H型鋼',
    'L',
    'U',
    '丸條',
    '加工',
    '圓管',
    '扁',
    '扁鐵',
    '捲門/伸縮門',
    '網',
    '角鐵',
    '鐵板',
  ] as const),
  '加工/孔': Object.freeze(['', '五金', '接頭', '角鐵', '鐵板', '門'] as const),
  其他: Object.freeze(['', '保麗龍', '加工', '手套', '曬衣架', '蜂巢紙', '配件'] as const),
  圓鐵: Object.freeze(['', '其他'] as const),
  '捲門/伸縮門': Object.freeze(['', '中柱', '其他', '底支', '遙控', '邊柱', '配件'] as const),
  網: Object.freeze(['', '刺網', '浪型網', '菱形網', '配件', '高床網', '點焊網'] as const),
  '格板/隔板': Object.freeze([''] as const),
  '五金/配件': Object.freeze([
    '',
    '伸縮器',
    '加工',
    '培林座',
    '壁虎',
    '彈簧',
    '後鈕',
    '扶手',
    '油漆',
    '焊條',
    '矽利康',
    '節竹鐵',
    '膠',
    '花管',
    '華司',
    '蜂巢紙',
    '螺帽',
    '螺母',
    '螺母/螺絲',
    '螺絲',
    '輪子',
    '配件',
    '配管',
    '釘',
    '鋸',
    '鑄花',
    '馬達箱',
  ] as const),
  '門窗/門板': Object.freeze(['', '窗花', '網', '角鐵', '配件', '門花'] as const),
  鐵板: Object.freeze(['', '圍籬板', '檔泥板', '特殊', '網板', '花板'] as const),
  '加工/折工': Object.freeze([
    '',
    '中柱',
    '其他',
    '切工',
    '工具箱',
    '消音',
    '無缺口',
    '特殊',
    '花板',
    '車斗',
    '鐵板',
    '門',
  ] as const),
  '加工/切工': Object.freeze([
    '',
    'H型鋼',
    'I型鋼/工字鐵',
    '圓管',
    '平鐵',
    '方管',
    '槽鐵',
    '角鐵',
    '鐵板',
    '板/浪板',
  ] as const),
  C型鋼: Object.freeze(['', '加工/其他'] as const),
  '板/浪板': Object.freeze(['', '五金/配件'] as const),
  方鐵: Object.freeze([''] as const),
  H型鋼: Object.freeze([''] as const),
  T型鋼: Object.freeze([''] as const),
  平鐵: Object.freeze([''] as const),
  角鐵: Object.freeze(['', '不等邊', '烤漆', '配件'] as const),
  圓管: Object.freeze(['', 'A管', 'B管', '圓條', '連料', '配管', '鋼管'] as const),
  鐵軌: Object.freeze([''] as const),
  槽鐵: Object.freeze([''] as const),
  'I型鋼/工字鐵': Object.freeze([''] as const),
  方管: Object.freeze(['', '連料'] as const),
  扁方管: Object.freeze([''] as const),
  '加工/開槽': Object.freeze(['', 'H型鋼'] as const),
}) satisfies Readonly<Record<PriceCategory, readonly string[]>>;

export type PriceSubcategory = (typeof registry)[PriceCategory][number];

export const priceSubcategoriesByCategory = registry;

const priceCategorySet = new Set<string>(priceCategories);

export function isPriceCategory(value: string): value is PriceCategory {
  return priceCategorySet.has(value);
}

export function isPriceSubcategory(
  category: PriceCategory,
  value: string,
): value is PriceSubcategory {
  return (priceSubcategoriesByCategory[category] as readonly string[]).includes(value);
}
