import type { SteelWorkbookColumn, SteelWorkbookSheet } from 'librechat-data-provider';

// Keep sheet/column structure in sync with docs/reference/訂單參考.xlsm; runtime must not read that file or seed quote data.
function column(
  key: string,
  label: string,
  valueType: SteelWorkbookColumn['valueType'] = 'text',
  editable = true,
  widthPx?: number,
): SteelWorkbookColumn {
  return {
    key,
    label,
    valueType,
    editable,
    ...(widthPx ? { widthPx } : {}),
  };
}

const quoteDetailColumns: SteelWorkbookColumn[] = [
  column('line_no', '項次', 'number', false, 72),
  column('customer_original_item_name', '客戶原始品名', 'text', true, 220),
  column('normalized_item_name', '標準化品名', 'text', true, 220),
  column('search_keywords', '搜尋關鍵字', 'text', true, 180),
  column('product_price_candidate_items', '產品價格候選品項', 'text', true, 240),
  column('adopted_product_price_item', '採用產品價格品項', 'text', true, 220),
  column('is_exact_match', '是否完全匹配', 'boolean', true, 120),
  column('rejected_candidate_reason', '未採用候選原因', 'text', true, 220),
  column('material_category', '材料類別', 'text', true, 120),
  column('material', '材質', 'text', true, 120),
  column('spec', '規格', 'text', true, 160),
  column('finished_length_m', '成品長度m', 'number', true, 120),
  column('quantity', '數量', 'number', true, 96),
  column('unit', '單位', 'text', true, 80),
  column('raw_material_length', '素材長度', 'text', true, 120),
  column('raw_material_piece_count', '素材支數', 'number', true, 120),
  column('finished_count_per_raw_material', '可裁成品數', 'number', true, 120),
  column('remainder_length_or_weight', '餘料長度/重量', 'text', true, 160),
  column('unit_weight_kg_per_m', '單位重量kg/m', 'number', true, 140),
  column('unit_weight_kg', '單重kg', 'number', true, 120),
  column('total_weight_kg', '總重kg', 'number', true, 120),
  column('weight_algorithm', '重量算法', 'text', true, 160),
  column('customer', '客戶', 'text', true, 140),
  column('customer_tier', '分級', 'text', true, 96),
  column('material_unit_price', '材料單價', 'currency', true, 120),
  column('material_unit_price_field', '材料單價欄位', 'text', true, 160),
  column('material_pricing_unit', '材料計價單位', 'text', true, 140),
  column('billable_quantity', '計價數量', 'number', true, 120),
  column('cutting_fee', '切工費', 'currency', true, 120),
  column('hole_fee', '孔費', 'currency', true, 120),
  column('slotting_fee', '開槽費', 'currency', true, 120),
  column('bending_fee', '折工費', 'currency', true, 120),
  column('other_fee', '其他費', 'currency', true, 120),
  column('subtotal', '小計', 'currency', false, 120),
  column('confidence', '信心等級', 'status', false, 120),
  column('low_confidence_reason', '低信心原因', 'text', true, 220),
  column('decision_evidence', '判斷依據', 'text', true, 240),
  column('suggested_review', '建議複核', 'text', true, 180),
  column('note', '備註', 'text', true, 240),
];

const workbookTemplateSheets: SteelWorkbookSheet[] = [
  {
    id: 'system_order',
    label: '系統訂單',
    columns: [
      column('company_code', '公司編號', 'text', true, 120),
      column('line_no', '項次', 'number', true, 72),
      column('warehouse_code', '倉庫編號', 'text', true, 120),
      column('model_code', '型號', 'text', true, 140),
      column('item_spec', '品名規格', 'text', true, 260),
      column('material_code', '材質編號', 'text', true, 120),
      column('factory_code', '廠別編號', 'text', true, 120),
      column('unit', '單位', 'text', true, 80),
      column('quantity', '數量', 'number', true, 96),
      column('unit_weight', '單重', 'number', true, 96),
      column('total_quantity', '總數', 'number', true, 96),
      column('unit_price', '單價', 'currency', true, 96),
      column('pricing_basis', '計價基準', 'text', true, 120),
      column('formula_code', '公式編號', 'text', true, 120),
      column('thickness', '厚度', 'number', true, 96),
      column('width', '寬度', 'number', true, 96),
      column('length', '長度', 'number', true, 96),
      column('category', '類別', 'text', true, 96),
      column('delivery_date', '交貨日期', 'date', true, 120),
      column('note', '備註', 'text', true, 220),
    ],
    rows: [
      {
        id: 'order_1',
        cells: {
          company_code: 'O-15',
          line_no: 10,
          warehouse_code: 'L',
          model_code: 'EQA0095',
          item_spec: '磨光圓鐵 3/8 (6M)｜3/8，6M',
          unit: '支',
          quantity: 100,
          unit_weight: 2.994,
          total_quantity: 100,
          unit_price: 180,
          pricing_basis: '口語轉換匹配',
          length: 6000,
          category: '圓鐵',
          note: '三分≈3/8≈9mm，採6M支價；人工複核：確認是否為磨光圓鐵或一般黑圓鐵',
        },
      },
      {
        id: 'order_2',
        cells: {
          company_code: 'O-15',
          line_no: 20,
          warehouse_code: 'L',
          model_code: 'GOB10151',
          item_spec: '黑B鋼管 1 1/2"*3.6｜1 1/2"，外徑48.3，t=3.6，6M',
          unit: '支',
          quantity: 20,
          total_quantity: 20,
          unit_price: 786.9,
          pricing_basis: '尺寸近似+常用規格預設',
          length: 6000,
          category: '圓管',
          note: '48.1近似48.3；厚度未提供，暫採黑B 3.6；人工複核：確認厚度/黑A或黑B',
        },
      },
      {
        id: 'order_3',
        cells: {
          company_code: 'O-15',
          line_no: 30,
          warehouse_code: 'L',
          model_code: 'ELB10025',
          item_spec: '黑角鐵25*2.5(5.68)｜25×25×2.5，6M',
          unit: '支',
          quantity: 100,
          unit_weight: 5.68,
          total_quantity: 100,
          unit_price: 172.1,
          pricing_basis: '口語轉換+常用規格預設',
          length: 6000,
          category: '角鐵',
          note: '1吋≈25mm；厚度未提供，暫採2.5；人工複核：確認厚度是否2.5或3.0',
        },
      },
      {
        id: 'order_4',
        cells: {
          company_code: 'O-15',
          line_no: 40,
          warehouse_code: 'L',
          model_code: 'ELB15025',
          item_spec: '黑角鐵38*2.5(8.76)｜38×38×2.5，6M',
          unit: '支',
          quantity: 70,
          unit_weight: 8.76,
          total_quantity: 70,
          unit_price: 250.54,
          pricing_basis: '口語轉換+常用規格預設',
          length: 6000,
          category: '角鐵',
          note: '1英半≈38mm；厚度未提供，暫採2.5；人工複核：確認厚度',
        },
      },
      {
        id: 'order_5',
        cells: {
          company_code: 'O-15',
          line_no: 50,
          warehouse_code: 'L',
          model_code: 'HMU010',
          item_spec: '彩色鋁鋅清板 暫估｜8呎/片；0.45厚度果綠五溝未有有效價',
          unit: '尺',
          quantity: 160,
          total_quantity: 160,
          unit_price: 43.5,
          pricing_basis: '替代有價品項',
          category: '浪板/圍籬板',
          note: '原果綠五溝售價0，暫採彩色鋁鋅清板B價；20片×8尺=160尺；人工複核：確認果青=果綠、板型五溝、0.45厚度與有效單價',
        },
      },
      {
        id: 'order_6',
        cells: {
          company_code: 'O-15',
          line_no: 60,
          warehouse_code: 'L',
          model_code: 'CCG07523',
          item_spec: '錏輕型鋼 75*2.3｜75×45×15×2.3，6M',
          unit: 'Kg',
          quantity: 780,
          unit_weight: 19.5,
          total_quantity: 780,
          unit_price: 26.8,
          pricing_basis: 'C型鋼專用規則+替代有價品項',
          length: 6000,
          category: 'C型鋼',
          note: 'C型鋼鋼捲抽料，不算餘料/切工/孔費；黑鐵C75售價0，暫採錏C75 B價kg；人工複核：確認材質是否錏；若黑鐵需有效單價',
        },
      },
      {
        id: 'order_7',
        cells: {
          company_code: 'O-15',
          line_no: 70,
          warehouse_code: 'L',
          model_code: 'BXH030408',
          item_spec: "錏花板 3.0*4'*8'切半｜3.0×4'×8'母材切成4'×4'",
          unit: '張',
          quantity: 2,
          total_quantity: 2,
          unit_price: 2281.6,
          pricing_basis: '最佳配料暫估',
          thickness: 3,
          category: '板材',
          note: '4片4×4由2張4×8切半；切工未列；人工複核：確認是否用4×8母材切半，切工是否另計',
        },
      },
      {
        id: 'order_8',
        cells: {
          company_code: 'O-15',
          line_no: 80,
          warehouse_code: 'L',
          model_code: 'BNG012408',
          item_spec: "錏板 1.2*4'*8'｜1.2×4'×8'",
          unit: '張',
          quantity: 30,
          unit_weight: 28.5,
          total_quantity: 30,
          unit_price: 897.75,
          pricing_basis: '替代有價品項',
          thickness: 1.2,
          category: '板材',
          note: '未找到脫辛次級品專價，暫採一般錏板1.2×4×8 B價；人工複核：確認是否有次級品專價',
        },
      },
      {
        id: 'order_9',
        cells: {
          company_code: 'O-15',
          line_no: 90,
          warehouse_code: 'L',
          model_code: '未確認',
          item_spec: 'L型鑄底 T=3.0｜T=3.0，尺寸未提供',
          unit: '片',
          quantity: 2000,
          total_quantity: 2000,
          unit_price: '未確認',
          pricing_basis: '無價格/缺尺寸',
          thickness: 3,
          category: '加工/折件',
          note: '只有厚度，缺長寬/展開尺寸/折刀數；人工複核：需提供尺寸或圖面、材質、折法、單價',
        },
      },
      {
        id: 'order_10',
        cells: {
          company_code: 'O-15',
          line_no: 100,
          warehouse_code: 'L',
          model_code: 'BNG012408',
          item_spec: "錏板 1.2*4'*8'配料暫估｜客需1.0×4'×5'；暫以1.2×4'×8'母材配料",
          unit: '張',
          quantity: 100,
          total_quantity: 100,
          unit_price: 897.75,
          pricing_basis: '替代有價品項+最佳配料暫估',
          thickness: 1,
          category: '板材',
          note: '4×8母材每張取1片4×5，餘4×3；1.0無有效價，暫採1.2錏板B價；人工複核：確認1.0×4×5計價方式、母材、餘料歸屬與有效單價',
        },
      },
    ],
  },
  {
    id: 'customer_data',
    label: '客戶資料',
    columns: [
      column('customer_code', '客戶編號', 'text', true, 120),
      column('vendor_name', '廠商名稱', 'text', true, 220),
      column('price_tier', '等級', 'text', true, 120),
      column('confirmation_status', '確認狀態', 'status', true, 140),
      column('note', '備註', 'text', true, 260),
    ],
    rows: [],
  },
  {
    id: 'quote_details',
    label: '報價明細',
    columns: quoteDetailColumns,
    rows: [
      {
        id: 'line_1',
        cells: {
          line_no: 1,
          customer_original_item_name: '三分圓鐵（6米）×100支',
          normalized_item_name: '磨光圓鐵 3/8 (6M)',
          search_keywords: '三分, 3/8, 9mm, 圓鐵, 磨光圓鐵, 6M',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2782；手冊圓鋼9mm重量0.499kg/m',
          adopted_product_price_item: 'EQA0095 磨光圓鐵 3/8 (6M)',
          is_exact_match: '否',
          material_category: '圓鐵',
          material: '黑鐵/磨光圓鐵',
          spec: '3/8，6M',
          finished_length_m: 6,
          quantity: 100,
          unit: '支',
          raw_material_length: '6M',
          unit_weight_kg_per_m: 0.499,
          unit_weight_kg: 2.994,
          total_weight_kg: 299.4,
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 180,
          material_unit_price_field: '售價B',
          material_pricing_unit: '支',
          billable_quantity: 100,
          subtotal: 18000,
          confidence: '中',
          low_confidence_reason: '口語轉換匹配',
          decision_evidence: '三分≈3/8≈9mm，採6M支價',
          suggested_review: '確認是否為磨光圓鐵或一般黑圓鐵',
        },
      },
      {
        id: 'line_2',
        cells: {
          line_no: 2,
          customer_original_item_name: '黑圓管48.1（6米）×20支',
          normalized_item_name: '黑B鋼管 1 1/2"*3.6',
          search_keywords: '黑圓管, 黑管, 黑A, 黑B, 48.1, 48.3, 1 1/2, 11/2',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 5733；手冊黑AB圓管1 1/2外徑48.3',
          adopted_product_price_item: 'GOB10151 黑B鋼管 1 1/2"*3.6',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '圓管',
          material: '黑鐵',
          spec: '1 1/2"，外徑48.3，t=3.6，6M',
          finished_length_m: 6,
          quantity: 20,
          unit: '支',
          raw_material_length: '6M',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 786.9,
          material_unit_price_field: '售價B',
          material_pricing_unit: '支',
          billable_quantity: 20,
          subtotal: 15738,
          confidence: '低',
          low_confidence_reason: '尺寸近似+常用規格預設',
          decision_evidence: '48.1近似48.3；厚度未提供，暫採黑B 3.6',
          suggested_review: '確認厚度/黑A或黑B',
        },
      },
      {
        id: 'line_3',
        cells: {
          line_no: 3,
          customer_original_item_name: '一英吋黑角鐵（6米）×100支',
          normalized_item_name: '黑角鐵25*2.5(5.68)',
          search_keywords: '一英吋, 1吋, 25mm, 黑角鐵, 三角鐵, 25*2.5, 6M',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2600；手冊等邊角鐵25×2.5為5.68kg/6M',
          adopted_product_price_item: 'ELB10025 黑角鐵25*2.5(5.68)',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '角鐵',
          material: '黑鐵',
          spec: '25×25×2.5，6M',
          finished_length_m: 6,
          quantity: 100,
          unit: '支',
          raw_material_length: '6M',
          unit_weight_kg_per_m: 0.95,
          unit_weight_kg: 5.68,
          total_weight_kg: 568,
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 172.1,
          material_unit_price_field: '售價B',
          material_pricing_unit: '支',
          billable_quantity: 100,
          subtotal: 17210,
          confidence: '低',
          low_confidence_reason: '口語轉換+常用規格預設',
          decision_evidence: '1吋≈25mm；厚度未提供，暫採2.5',
          suggested_review: '確認厚度是否2.5或3.0',
        },
      },
      {
        id: 'line_4',
        cells: {
          line_no: 4,
          customer_original_item_name: '一英半吋黑角鐵（6米）×70支',
          normalized_item_name: '黑角鐵38*2.5(8.76)',
          search_keywords: '一英半, 1 1/2, 38mm, 黑角鐵, 三角鐵, 38*2.5, 6M',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2612；手冊等邊角鐵38×2.5為8.76kg/6M',
          adopted_product_price_item: 'ELB15025 黑角鐵38*2.5(8.76)',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '角鐵',
          material: '黑鐵',
          spec: '38×38×2.5，6M',
          finished_length_m: 6,
          quantity: 70,
          unit: '支',
          raw_material_length: '6M',
          unit_weight_kg_per_m: 1.46,
          unit_weight_kg: 8.76,
          total_weight_kg: 613.2,
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 250.54,
          material_unit_price_field: '售價B',
          material_pricing_unit: '支',
          billable_quantity: 70,
          subtotal: 17538,
          confidence: '低',
          low_confidence_reason: '口語轉換+常用規格預設',
          decision_evidence: '1英半≈38mm；厚度未提供，暫採2.5',
          suggested_review: '確認厚度',
        },
      },
      {
        id: 'line_5',
        cells: {
          line_no: 5,
          customer_original_item_name: '果青板（綠色）0.45×8呎*20片',
          normalized_item_name: '彩色鋁鋅清板 暫估',
          search_keywords: '果青, 果綠, 綠色, 烤漆, 彩色鋁鋅, 五溝, 圍籬板, 0.45, 8呎',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / rows 4494-4495售價0；row 5990彩色鋁鋅清板B價43.5',
          adopted_product_price_item: 'HMU010 彩色鋁鋅清板 暫估',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '浪板/圍籬板',
          material: '彩色鋁鋅/烤漆暫估',
          spec: '8呎/片；0.45厚度果綠五溝未有有效價',
          quantity: 20,
          unit: '片',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 43.5,
          material_unit_price_field: '售價B',
          material_pricing_unit: '尺',
          billable_quantity: 160,
          subtotal: 6960,
          confidence: '低',
          low_confidence_reason: '替代有價品項',
          decision_evidence: '原果綠五溝售價0，暫採彩色鋁鋅清板B價；20片×8尺=160尺',
          suggested_review: '確認果青=果綠、板型五溝、0.45厚度與有效單價',
        },
      },
      {
        id: 'line_6',
        cells: {
          line_no: 6,
          customer_original_item_name: 'C75型鋼（6米）×40支',
          normalized_item_name: '錏輕型鋼 75*2.3',
          search_keywords: 'C75, C型鋼, 錏C, 75*45*15, 2.3, 輕型鋼',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 1558；手冊C75×45×15×2.3為3.25kg/m',
          adopted_product_price_item: 'CCG07523 錏輕型鋼 75*2.3',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: 'C型鋼',
          material: '錏',
          spec: '75×45×15×2.3，6M',
          finished_length_m: 6,
          quantity: 40,
          unit: '支',
          raw_material_length: '不適用-C型鋼鋼捲抽料',
          raw_material_piece_count: '不適用-C型鋼鋼捲抽料',
          finished_count_per_raw_material: '不適用-C型鋼鋼捲抽料',
          remainder_length_or_weight: '不適用-C型鋼鋼捲抽料',
          unit_weight_kg_per_m: 3.25,
          unit_weight_kg: 19.5,
          total_weight_kg: 780,
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 26.8,
          material_unit_price_field: '售價B',
          material_pricing_unit: 'Kg',
          billable_quantity: 780,
          cutting_fee: 0,
          hole_fee: 0,
          subtotal: 20904,
          confidence: '低',
          low_confidence_reason: 'C型鋼專用規則+替代有價品項',
          decision_evidence: 'C型鋼鋼捲抽料，不算餘料/切工/孔費；黑鐵C75售價0，暫採錏C75 B價kg',
          suggested_review: '確認材質是否錏；若黑鐵需有效單價',
        },
      },
      {
        id: 'line_7',
        cells: {
          line_no: 7,
          customer_original_item_name: '亞花板3.0×4呎×4呎×4片',
          normalized_item_name: "錏花板 3.0*4'*8'切半",
          search_keywords: '亞花板, 錏花板, 3.0, 4*4, 4*8, 切半',
          product_price_candidate_items: '產品價格.xlsx / Sheet1 / row 1517',
          adopted_product_price_item: "BXH030408 錏花板 3.0*4'*8'切半",
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '板材',
          material: '錏花板',
          spec: "3.0×4'×8'母材切成4'×4'",
          quantity: 4,
          unit: '片',
          raw_material_length: '4×8母材',
          raw_material_piece_count: 2,
          finished_count_per_raw_material: 2,
          remainder_length_or_weight: '無/切半',
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 2281.6,
          material_unit_price_field: '售價B',
          material_pricing_unit: '張',
          billable_quantity: 2,
          subtotal: 4563,
          confidence: '低',
          low_confidence_reason: '最佳配料暫估',
          decision_evidence: '4片4×4由2張4×8切半；切工未列',
          suggested_review: '確認是否用4×8母材切半，切工是否另計',
        },
      },
      {
        id: 'line_8',
        cells: {
          line_no: 8,
          customer_original_item_name: '脫辛次級品鍍鋅板1.2×4呎×8呎×30片',
          normalized_item_name: "錏板 1.2*4'*8'",
          search_keywords: '脫辛, 次級品, 鍍鋅板, 錏板, 1.2, 4*8',
          product_price_candidate_items: '產品價格.xlsx / Sheet1 / row 1372',
          adopted_product_price_item: "BNG012408 錏板 1.2*4'*8'",
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '板材',
          material: '鍍鋅/錏板',
          spec: "1.2×4'×8'",
          quantity: 30,
          unit: '片',
          unit_weight_kg: 28.5,
          total_weight_kg: 855,
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 897.75,
          material_unit_price_field: '售價B',
          material_pricing_unit: '張',
          billable_quantity: 30,
          subtotal: 26932,
          confidence: '低',
          low_confidence_reason: '替代有價品項',
          decision_evidence: '未找到脫辛次級品專價，暫採一般錏板1.2×4×8 B價',
          suggested_review: '確認是否有次級品專價',
        },
      },
      {
        id: 'line_9',
        cells: {
          line_no: 9,
          customer_original_item_name: 'L型鑄底T=3.0×2000片（另外送）',
          normalized_item_name: 'L型鑄底 T=3.0',
          search_keywords: 'L型鑄底, 鑄底, L型, T=3.0, 折件',
          product_price_candidate_items: '產品價格.xlsx 未找到明確鑄底品項',
          adopted_product_price_item: '未確認 L型鑄底 T=3.0',
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '加工/折件',
          material: '未確認',
          spec: 'T=3.0，尺寸未提供',
          quantity: 2000,
          unit: '片',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: '未確認',
          material_unit_price_field: '售價B',
          material_pricing_unit: '片',
          billable_quantity: 2000,
          subtotal: '未確認',
          confidence: '低',
          low_confidence_reason: '無價格/缺尺寸',
          decision_evidence: '只有厚度，缺長寬/展開尺寸/折刀數',
          suggested_review: '需提供尺寸或圖面、材質、折法、單價',
          note: '第9-10項另外送',
        },
      },
      {
        id: 'line_10',
        cells: {
          line_no: 10,
          customer_original_item_name: '鍍鋅板1.0×4呎×5呎×100片（另外送）',
          normalized_item_name: "錏板 1.2*4'*8'配料暫估",
          search_keywords: '鍍鋅板, 錏板, 1.0, 4*5, 4*8, 裁切, 配料',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 1370 1.0×4×8售價0；row 1372 1.2×4×8有B價',
          adopted_product_price_item: "BNG012408 錏板 1.2*4'*8'配料暫估",
          is_exact_match: '否',
          rejected_candidate_reason: '依最相關資料暫估，需人工複核',
          material_category: '板材',
          material: '鍍鋅/錏板',
          spec: "客需1.0×4'×5'；暫以1.2×4'×8'母材配料",
          quantity: 100,
          unit: '片',
          raw_material_length: '4×8母材',
          raw_material_piece_count: 100,
          finished_count_per_raw_material: 1,
          remainder_length_or_weight: '4×3餘料/張',
          weight_algorithm: '依手冊/價格表單位重或母材配料',
          customer: '世和',
          customer_tier: 'B級',
          material_unit_price: 897.75,
          material_unit_price_field: '售價B',
          material_pricing_unit: '張',
          billable_quantity: 100,
          subtotal: 89775,
          confidence: '低',
          low_confidence_reason: '替代有價品項+最佳配料暫估',
          decision_evidence: '4×8母材每張取1片4×5，餘4×3；1.0無有效價，暫採1.2錏板B價',
          suggested_review: '確認1.0×4×5計價方式、母材、餘料歸屬與有效單價',
          note: '第9-10項另外送',
        },
      },
    ],
  },
  {
    id: 'summary',
    label: '總結',
    columns: [column('item', '項目'), column('value', '值'), column('note', '備註')],
    rows: [
      {
        id: 'summary_customer',
        cells: {
          item: '客戶暫採',
          value: '世和',
          note: '客戶資料另有世和金屬A級候選，需複核',
        },
      },
      { id: 'summary_customer_code', cells: { item: '客戶編號暫採', value: 'O-15' } },
      {
        id: 'summary_customer_tier',
        cells: {
          item: '分級暫採',
          value: 'B級',
          note: '依最相關客戶名稱；樹林一廠地址未完全對上',
        },
      },
      {
        id: 'summary_delivery_address',
        cells: { item: '送貨地址', value: '新北市樹林區柑園街一段271-4號' },
      },
      {
        id: 'summary_contact',
        cells: { item: '聯繫人', value: '王俊弼 02-26687981 / 辦公室2668-7981' },
      },
      {
        id: 'summary_first_delivery_amount',
        cells: { item: '本次先送第1-8項暫估金額', value: 127845, note: '含低信心暫估' },
      },
      {
        id: 'summary_extra_delivery_amount',
        cells: {
          item: '第9-10項另外送已確認暫估金額',
          value: 89775,
          note: '第9項未確認，第10項暫估',
        },
      },
      {
        id: 'summary_total_amount',
        cells: { item: '報價總額', value: 217620, note: '不含未確認第9項' },
      },
      {
        id: 'summary_unconfirmed_count',
        cells: { item: '未確認項目數', value: 1, note: '單價/尺寸不全' },
      },
      {
        id: 'summary_low_confidence_count',
        cells: { item: '低信心項目數', value: 9, note: '需人工複核' },
      },
      {
        id: 'summary_total_weight',
        cells: { item: '總重量可計算kg', value: 3115.6, note: '僅含有重量資料項目' },
      },
      {
        id: 'summary_c_type_rule',
        cells: { item: 'C型鋼規則', value: '套用', note: '不算餘料、不列一般切工、不列孔費' },
      },
    ],
  },
  {
    id: 'manual_review',
    label: '人工複核',
    columns: [
      column('line_no', '項次', 'number', true, 72),
      column('issue_type', '問題類型', 'text', true, 140),
      column('estimated_value', '暫估值', 'text', true, 160),
      column('low_confidence_reason', '低信心原因', 'text', true, 220),
      column('inferred_evidence', '推定依據', 'text', true, 240),
      column('confirmation_needed', '需確認內容', 'text', true, 240),
      column('amount_impact', '金額影響', 'currency', true, 120),
      column('suggested_action', '建議處理', 'text', true, 220),
    ],
    rows: [
      {
        id: 'review_customer_tier',
        cells: {
          line_no: '全部',
          issue_type: '客戶分級複核',
          estimated_value: '暫用世和O-15 B級',
          low_confidence_reason: '樹林一廠地址未對上客戶表；有世和金屬A級候選',
          inferred_evidence: '客戶名稱最接近世和，但地點與聯絡資訊需確認',
          confirmation_needed: '確認實際客戶代號與分級',
          amount_impact: '影響全部單價',
          suggested_action: '確認後重算',
        },
      },
      {
        id: 'review_2',
        cells: {
          line_no: 2,
          issue_type: '尺寸近似+常用規格預設',
          estimated_value: 'GOB10151 / 786.9',
          low_confidence_reason: '確認厚度/黑A或黑B',
          inferred_evidence: '48.1近似48.3；厚度未提供，暫採黑B 3.6',
          confirmation_needed: '確認厚度/黑A或黑B',
          amount_impact: 15738,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_3',
        cells: {
          line_no: 3,
          issue_type: '口語轉換+常用規格預設',
          estimated_value: 'ELB10025 / 172.1',
          low_confidence_reason: '確認厚度是否2.5或3.0',
          inferred_evidence: '1吋≈25mm；厚度未提供，暫採2.5',
          confirmation_needed: '確認厚度是否2.5或3.0',
          amount_impact: 17210,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_4',
        cells: {
          line_no: 4,
          issue_type: '口語轉換+常用規格預設',
          estimated_value: 'ELB15025 / 250.54',
          low_confidence_reason: '確認厚度',
          inferred_evidence: '1英半≈38mm；厚度未提供，暫採2.5',
          confirmation_needed: '確認厚度',
          amount_impact: 17538,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_5',
        cells: {
          line_no: 5,
          issue_type: '替代有價品項',
          estimated_value: 'HMU010 / 43.5',
          low_confidence_reason: '確認果青=果綠、板型五溝、0.45厚度與有效單價',
          inferred_evidence: '原果綠五溝售價0，暫採彩色鋁鋅清板B價；20片×8尺=160尺',
          confirmation_needed: '確認果青=果綠、板型五溝、0.45厚度與有效單價',
          amount_impact: 6960,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_6',
        cells: {
          line_no: 6,
          issue_type: 'C型鋼專用規則+替代有價品項',
          estimated_value: 'CCG07523 / 26.8',
          low_confidence_reason: '確認材質是否錏；若黑鐵需有效單價',
          inferred_evidence: 'C型鋼鋼捲抽料，不算餘料/切工/孔費；黑鐵C75售價0，暫採錏C75 B價kg',
          confirmation_needed: '確認材質是否錏；若黑鐵需有效單價',
          amount_impact: 20904,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_7',
        cells: {
          line_no: 7,
          issue_type: '最佳配料暫估',
          estimated_value: 'BXH030408 / 2281.6',
          low_confidence_reason: '確認是否用4×8母材切半，切工是否另計',
          inferred_evidence: '4片4×4由2張4×8切半；切工未列',
          confirmation_needed: '確認是否用4×8母材切半，切工是否另計',
          amount_impact: 4563,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_8',
        cells: {
          line_no: 8,
          issue_type: '替代有價品項',
          estimated_value: 'BNG012408 / 897.75',
          low_confidence_reason: '確認是否有次級品專價',
          inferred_evidence: '未找到脫辛次級品專價，暫採一般錏板1.2×4×8 B價',
          confirmation_needed: '確認是否有次級品專價',
          amount_impact: 26932,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_9',
        cells: {
          line_no: 9,
          issue_type: '無價格/缺尺寸',
          estimated_value: '未確認 / 未確認',
          low_confidence_reason: '需提供尺寸或圖面、材質、折法、單價',
          inferred_evidence: '只有厚度，缺長寬/展開尺寸/折刀數',
          confirmation_needed: '需提供尺寸或圖面、材質、折法、單價',
          amount_impact: '未確認',
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
      {
        id: 'review_10',
        cells: {
          line_no: 10,
          issue_type: '替代有價品項+最佳配料暫估',
          estimated_value: 'BNG012408 / 897.75',
          low_confidence_reason: '確認1.0×4×5計價方式、母材、餘料歸屬與有效單價',
          inferred_evidence: '4×8母材每張取1片4×5，餘4×3；1.0無有效價，暫採1.2錏板B價',
          confirmation_needed: '確認1.0×4×5計價方式、母材、餘料歸屬與有效單價',
          amount_impact: 89775,
          suggested_action: '確認後更新系統訂單與價格來源',
        },
      },
    ],
  },
  {
    id: 'price_sources',
    label: '價格來源',
    columns: [
      column('customer', '客戶', 'text', true, 140),
      column('customer_tier', '分級', 'text', true, 96),
      column('customer_original_item_name', '客戶原始品名', 'text', true, 220),
      column('normalized_item_name', '標準化品名', 'text', true, 220),
      column('search_keywords', '搜尋關鍵字', 'text', true, 180),
      column('product_price_candidate_items', '產品價格候選品項', 'text', true, 240),
      column('adopted_product_price_item', '採用產品價格品項', 'text', true, 220),
      column('adopted_unit_price', '採用單價', 'currency', true, 120),
      column('unit_price_field', '單價欄位', 'text', true, 140),
      column('unit', '單位', 'text', true, 80),
      column('source_file', '來源檔案', 'text', false, 180),
      column('worksheet', '工作表', 'text', false, 140),
      column('row_or_page', '列號或頁碼', 'text', false, 120),
      column('is_exact_match', '是否精準匹配', 'boolean', true, 140),
      column('difference_note', '差異說明', 'text', true, 220),
      column('confidence', '信心等級', 'status', false, 120),
      column('note', '備註', 'text', true, 220),
    ],
    rows: [
      {
        id: 'source_1',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '三分圓鐵（6米）×100支',
          normalized_item_name: '磨光圓鐵 3/8 (6M)',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2782；手冊圓鋼9mm重量0.499kg/m',
          adopted_product_price_item: 'EQA0095 磨光圓鐵 3/8 (6M)',
          adopted_unit_price: 180,
          unit_price_field: '售價B',
          unit: '支',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '2782',
          is_exact_match: '否',
          difference_note: '三分≈3/8≈9mm，採6M支價',
          confidence: '中',
          note: '確認是否為磨光圓鐵或一般黑圓鐵',
        },
      },
      {
        id: 'source_2',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '黑圓管48.1（6米）×20支',
          normalized_item_name: '黑B鋼管 1 1/2"*3.6',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 5733；手冊黑AB圓管1 1/2外徑48.3',
          adopted_product_price_item: 'GOB10151 黑B鋼管 1 1/2"*3.6',
          adopted_unit_price: 786.9,
          unit_price_field: '售價B',
          unit: '支',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '5733',
          is_exact_match: '否',
          difference_note: '48.1近似48.3；厚度未提供，暫採黑B 3.6',
          confidence: '低',
          note: '確認厚度/黑A或黑B',
        },
      },
      {
        id: 'source_3',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '一英吋黑角鐵（6米）×100支',
          normalized_item_name: '黑角鐵25*2.5(5.68)',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2600；手冊等邊角鐵25×2.5為5.68kg/6M',
          adopted_product_price_item: 'ELB10025 黑角鐵25*2.5(5.68)',
          adopted_unit_price: 172.1,
          unit_price_field: '售價B',
          unit: '支',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '2600',
          is_exact_match: '否',
          difference_note: '1吋≈25mm；厚度未提供，暫採2.5',
          confidence: '低',
          note: '確認厚度是否2.5或3.0',
        },
      },
      {
        id: 'source_4',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '一英半吋黑角鐵（6米）×70支',
          normalized_item_name: '黑角鐵38*2.5(8.76)',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 2612；手冊等邊角鐵38×2.5為8.76kg/6M',
          adopted_product_price_item: 'ELB15025 黑角鐵38*2.5(8.76)',
          adopted_unit_price: 250.54,
          unit_price_field: '售價B',
          unit: '支',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '2612',
          is_exact_match: '否',
          difference_note: '1英半≈38mm；厚度未提供，暫採2.5',
          confidence: '低',
          note: '確認厚度',
        },
      },
      {
        id: 'source_5',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '果青板（綠色）0.45×8呎*20片',
          normalized_item_name: '彩色鋁鋅清板 暫估',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / rows 4494-4495售價0；row 5990彩色鋁鋅清板B價43.5',
          adopted_product_price_item: 'HMU010 彩色鋁鋅清板 暫估',
          adopted_unit_price: 43.5,
          unit_price_field: '售價B',
          unit: '尺',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '4494/4495/5990',
          is_exact_match: '否',
          difference_note: '原果綠五溝售價0，暫採彩色鋁鋅清板B價；20片×8尺=160尺',
          confidence: '低',
          note: '確認果青=果綠、板型五溝、0.45厚度與有效單價',
        },
      },
      {
        id: 'source_6',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: 'C75型鋼（6米）×40支',
          normalized_item_name: '錏輕型鋼 75*2.3',
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 1558；手冊C75×45×15×2.3為3.25kg/m',
          adopted_product_price_item: 'CCG07523 錏輕型鋼 75*2.3',
          adopted_unit_price: 26.8,
          unit_price_field: '售價B',
          unit: 'Kg',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '1531/1558',
          is_exact_match: '否',
          difference_note: 'C型鋼鋼捲抽料，不算餘料/切工/孔費；黑鐵C75售價0，暫採錏C75 B價kg',
          confidence: '低',
          note: '確認材質是否錏；若黑鐵需有效單價',
        },
      },
      {
        id: 'source_7',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '亞花板3.0×4呎×4呎×4片',
          normalized_item_name: "錏花板 3.0*4'*8'切半",
          product_price_candidate_items: '產品價格.xlsx / Sheet1 / row 1517',
          adopted_product_price_item: "BXH030408 錏花板 3.0*4'*8'切半",
          adopted_unit_price: 2281.6,
          unit_price_field: '售價B',
          unit: '張',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '1517',
          is_exact_match: '否',
          difference_note: '4片4×4由2張4×8切半；切工未列',
          confidence: '低',
          note: '確認是否用4×8母材切半，切工是否另計',
        },
      },
      {
        id: 'source_8',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '脫辛次級品鍍鋅板1.2×4呎×8呎×30片',
          normalized_item_name: "錏板 1.2*4'*8'",
          product_price_candidate_items: '產品價格.xlsx / Sheet1 / row 1372',
          adopted_product_price_item: "BNG012408 錏板 1.2*4'*8'",
          adopted_unit_price: 897.75,
          unit_price_field: '售價B',
          unit: '張',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '1372',
          is_exact_match: '否',
          difference_note: '未找到脫辛次級品專價，暫採一般錏板1.2×4×8 B價',
          confidence: '低',
          note: '確認是否有次級品專價',
        },
      },
      {
        id: 'source_9',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: 'L型鑄底T=3.0×2000片（另外送）',
          normalized_item_name: 'L型鑄底 T=3.0',
          product_price_candidate_items: '產品價格.xlsx 未找到明確鑄底品項',
          adopted_product_price_item: '未確認 L型鑄底 T=3.0',
          adopted_unit_price: '未確認',
          unit_price_field: '售價B',
          unit: '片',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '未找到',
          is_exact_match: '否',
          difference_note: '只有厚度，缺長寬/展開尺寸/折刀數',
          confidence: '低',
          note: '需提供尺寸或圖面、材質、折法、單價',
        },
      },
      {
        id: 'source_10',
        cells: {
          customer: '世和',
          customer_tier: 'B級',
          customer_original_item_name: '鍍鋅板1.0×4呎×5呎×100片（另外送）',
          normalized_item_name: "錏板 1.2*4'*8'配料暫估",
          product_price_candidate_items:
            '產品價格.xlsx / Sheet1 / row 1370 1.0×4×8售價0；row 1372 1.2×4×8有B價',
          adopted_product_price_item: "BNG012408 錏板 1.2*4'*8'配料暫估",
          adopted_unit_price: 897.75,
          unit_price_field: '售價B',
          unit: '張',
          source_file: '產品價格.xlsx',
          worksheet: 'Sheet1',
          row_or_page: '1370/1372',
          is_exact_match: '否',
          difference_note: '4×8母材每張取1片4×5，餘4×3；1.0無有效價，暫採1.2錏板B價',
          confidence: '低',
          note: '確認1.0×4×5計價方式、母材、餘料歸屬與有效單價',
        },
      },
    ],
  },
  {
    id: 'interpretation_notes',
    label: '判讀備註',
    columns: [
      column('item', '項目', 'text', true, 160),
      column('content', '內容', 'text', true, 320),
      column('confidence', '信心', 'status', false, 120),
      column('evidence', '依據', 'text', false, 240),
    ],
    rows: [
      {
        id: 'note_1',
        cells: {
          item: '整體處理規則',
          content:
            '依現在 project instruction：先用最相關資料處理，口語/近似/替代資料全部標記人工複核。',
          confidence: '中',
          evidence: '使用者前述確認：先用最相關數據處理，標記人工複查',
        },
      },
      {
        id: 'note_2',
        cells: {
          item: '客戶分級',
          content: '暫採世和O-15 B級；另有世和金屬A級候選',
          confidence: '低',
          evidence: '客戶資料.xlsx',
        },
      },
      {
        id: 'note_3',
        cells: {
          item: 'C型鋼',
          content: 'C75套用C型鋼專用計價規則：鋼捲抽料，不算素材支數、餘料、一般切工、孔費',
          confidence: '中',
          evidence: 'project instruction / 產品價格.xlsx / 龍頂手冊',
        },
      },
      {
        id: 'note_4',
        cells: {
          item: '第9-10項',
          content: '第9及10項標示另外送，仍列入系統訂單；第9未確認，第10暫估',
          confidence: '低',
          evidence: '使用者文字訂單',
        },
      },
      {
        id: 'note_5',
        cells: {
          item: '未確認不可填0',
          content: '售價為0的品項改採最相關有價品項或標未確認',
          confidence: '中',
          evidence: 'project instruction',
        },
      },
    ],
  },
  {
    id: 'customer_quote',
    label: '報價單',
    columns: [
      column('line_no', '項次', 'number', true, 72),
      column('item_spec', '品名規格', 'text', true, 260),
      column('quantity', '數量', 'number', true, 96),
      column('unit', '單位', 'text', true, 80),
      column('unit_price', '單價', 'currency', true, 120),
      column('subtotal', '小計', 'currency', false, 120),
      column('note', '備註', 'text', true, 220),
    ],
    rows: [
      {
        id: 'customer_1',
        cells: {
          line_no: 1,
          item_spec: '三分圓鐵（6米）×100支',
          quantity: 100,
          unit: '支',
          unit_price: 180,
          subtotal: 18000,
        },
      },
      {
        id: 'customer_2',
        cells: {
          line_no: 2,
          item_spec: '黑圓管48.1（6米）×20支',
          quantity: 20,
          unit: '支',
          unit_price: 786.9,
          subtotal: 15738,
          note: '待確認',
        },
      },
      {
        id: 'customer_3',
        cells: {
          line_no: 3,
          item_spec: '一英吋黑角鐵（6米）×100支',
          quantity: 100,
          unit: '支',
          unit_price: 172.1,
          subtotal: 17210,
          note: '待確認',
        },
      },
      {
        id: 'customer_4',
        cells: {
          line_no: 4,
          item_spec: '一英半吋黑角鐵（6米）×70支',
          quantity: 70,
          unit: '支',
          unit_price: 250.54,
          subtotal: 17538,
          note: '待確認',
        },
      },
      {
        id: 'customer_5',
        cells: {
          line_no: 5,
          item_spec: '果青板（綠色）0.45×8呎*20片',
          quantity: 20,
          unit: '片',
          unit_price: 43.5,
          subtotal: 6960,
          note: '待確認',
        },
      },
      {
        id: 'customer_6',
        cells: {
          line_no: 6,
          item_spec: 'C75型鋼（6米）×40支',
          quantity: 40,
          unit: '支',
          unit_price: 26.8,
          subtotal: 20904,
          note: '待確認',
        },
      },
      {
        id: 'customer_7',
        cells: {
          line_no: 7,
          item_spec: '亞花板3.0×4呎×4呎×4片',
          quantity: 4,
          unit: '片',
          unit_price: 2281.6,
          subtotal: 4563,
          note: '待確認',
        },
      },
      {
        id: 'customer_8',
        cells: {
          line_no: 8,
          item_spec: '脫辛次級品鍍鋅板1.2×4呎×8呎×30片',
          quantity: 30,
          unit: '片',
          unit_price: 897.75,
          subtotal: 26932,
          note: '待確認',
        },
      },
      {
        id: 'customer_9',
        cells: {
          line_no: 9,
          item_spec: 'L型鑄底T=3.0×2000片（另外送）',
          quantity: 2000,
          unit: '片',
          unit_price: '未確認',
          subtotal: '未確認',
          note: '待確認',
        },
      },
      {
        id: 'customer_10',
        cells: {
          line_no: 10,
          item_spec: '鍍鋅板1.0×4呎×5呎×100片（另外送）',
          quantity: 100,
          unit: '片',
          unit_price: 897.75,
          subtotal: 89775,
          note: '待確認',
        },
      },
      { id: 'customer_total', cells: { unit_price: '報價總額' } },
    ],
  },
];

export function createInitialSheets(): SteelWorkbookSheet[] {
  return workbookTemplateSheets.map((sheet) => ({
    ...sheet,
    columns: sheet.columns.map((workbookColumn) => ({ ...workbookColumn })),
    rows: [],
  }));
}
