BEGIN;

ALTER TABLE steel.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.cutting_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.formula_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE steel.rules DISABLE ROW LEVEL SECURITY;

COMMIT;
