DROP INDEX IF EXISTS steel.prices_review_active_idx;

ALTER TABLE steel.prices
  DROP CONSTRAINT IF EXISTS prices_review_state_check,
  DROP COLUMN IF EXISTS review_state;

DROP TABLE IF EXISTS steel.cutting_prices CASCADE;

CREATE TABLE steel.cutting_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cutting_category TEXT NOT NULL,
  record_type TEXT NOT NULL,
  item_name TEXT NOT NULL,
  cut_type TEXT NOT NULL,
  spec_text TEXT,
  normalized_spec_text TEXT,
  inch_min NUMERIC(18, 9),
  inch_max NUMERIC(18, 9),
  mm_min NUMERIC(18, 9),
  mm_max NUMERIC(18, 9),
  unit TEXT,
  unit_price_a NUMERIC(18, 4),
  unit_price_b NUMERIC(18, 4),
  unit_price_c NUMERIC(18, 4),
  unit_price_f NUMERIC(18, 4),
  conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculation_rule TEXT,
  notes TEXT,
  source_sheet TEXT NOT NULL,
  source_row INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cutting_prices_record_type_check
  CHECK (record_type IN ('price', 'supplement')),
  CONSTRAINT cutting_prices_required_text_check
  CHECK (
    BTRIM(cutting_category) <> ''
    AND BTRIM(item_name) <> ''
    AND BTRIM(cut_type) <> ''
    AND BTRIM(source_sheet) <> ''
  ),
  CONSTRAINT cutting_prices_source_row_check
  CHECK (source_row > 0),
  CONSTRAINT cutting_prices_source_row_unique
  UNIQUE (source_sheet, source_row),
  CONSTRAINT cutting_prices_conditions_check
  CHECK (jsonb_typeof(conditions) = 'object'),
  CONSTRAINT cutting_prices_values_check
  CHECK (
    (unit_price_a IS NULL OR unit_price_a >= 0)
    AND (unit_price_b IS NULL OR unit_price_b >= 0)
    AND (unit_price_c IS NULL OR unit_price_c >= 0)
    AND (unit_price_f IS NULL OR unit_price_f >= 0)
    AND (
      (
        inch_min IS NULL AND inch_max IS NULL
        AND mm_min IS NULL AND mm_max IS NULL
      )
      OR (
        inch_min IS NOT NULL AND inch_max IS NOT NULL
        AND mm_min IS NOT NULL AND mm_max IS NOT NULL
        AND inch_min >= 0 AND inch_min <= inch_max
        AND mm_min >= 0 AND mm_min <= mm_max
        AND mm_min = ROUND(inch_min * 25.4, 9)
        AND mm_max = ROUND(inch_max * 25.4, 9)
      )
    )
  ),
  CONSTRAINT cutting_prices_supplement_check
  CHECK (
    record_type = 'price'
    OR (
      unit IS NULL
      AND unit_price_a IS NULL
      AND unit_price_b IS NULL
      AND unit_price_c IS NULL
      AND unit_price_f IS NULL
    )
  )
);

CREATE INDEX cutting_prices_category_trgm_idx
ON steel.cutting_prices USING GIN (cutting_category gin_trgm_ops);

CREATE INDEX cutting_prices_record_type_idx
ON steel.cutting_prices (record_type, cutting_category);

COMMENT ON TABLE steel.cutting_prices IS
'Cutting price and supplemental rule catalog atomically imported from docs/reference/切工價錢-clean.xlsx.';

DROP TRIGGER IF EXISTS set_cutting_prices_updated_at ON steel.cutting_prices;
CREATE TRIGGER set_cutting_prices_updated_at
BEFORE UPDATE ON steel.cutting_prices
FOR EACH ROW
EXECUTE FUNCTION steel.set_updated_at();
