CREATE TABLE IF NOT EXISTS steel.product_name_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_product_name TEXT NOT NULL,
  target_product_name TEXT NOT NULL,
  catalog_family TEXT REFERENCES steel.catalog_families(key),
  priority INTEGER NOT NULL DEFAULT 100,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT product_name_aliases_source_not_blank_check CHECK (
    btrim(source_product_name) <> ''
  ),
  CONSTRAINT product_name_aliases_target_not_blank_check CHECK (
    btrim(target_product_name) <> ''
  ),
  CONSTRAINT product_name_aliases_priority_check CHECK (priority >= 0),
  CONSTRAINT product_name_aliases_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT product_name_aliases_metadata_check CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT product_name_aliases_source_refs_check CHECK (jsonb_typeof(source_refs) = 'array')
);

CREATE UNIQUE INDEX IF NOT EXISTS product_name_aliases_source_target_unique
ON steel.product_name_aliases (
  lower(source_product_name),
  lower(target_product_name),
  COALESCE(catalog_family, '')
);

CREATE INDEX IF NOT EXISTS product_name_aliases_source_lookup_idx
ON steel.product_name_aliases (
  lower(source_product_name),
  active,
  review_state,
  priority,
  id
);

CREATE INDEX IF NOT EXISTS product_name_aliases_source_trgm_idx
ON steel.product_name_aliases USING GIN (source_product_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS product_name_aliases_target_trgm_idx
ON steel.product_name_aliases USING GIN (target_product_name gin_trgm_ops);

COMMENT ON TABLE steel.product_name_aliases IS
  'Admin-reviewed product-name lookup aliases used by search_price_candidates to expand oral or family names into price-row product names.';

COMMENT ON COLUMN steel.product_name_aliases.source_product_name IS
  'Oral, family, typo, or customer-provided product-name text from the AI search term.';

COMMENT ON COLUMN steel.product_name_aliases.target_product_name IS
  'Reviewed product-name text to search in steel.price_items.product_name.';

INSERT INTO steel.product_name_aliases (
  source_product_name,
  target_product_name,
  catalog_family,
  priority,
  review_state,
  source_refs
)
VALUES
  (
    'C',
    '錏輕型鋼',
    'c_type',
    45,
    'reviewed',
    jsonb_build_array(
      jsonb_build_object(
        'channel', 'repo_docs',
        'factType', 'product_name_alias',
        'sourceFile', 'docs/rules/鋼材規則.txt',
        'locator', 'c_type_default_galvanized_alias'
      )
    )
  ),
  (
    'C型鋼',
    '錏輕型鋼',
    'c_type',
    50,
    'reviewed',
    jsonb_build_array(
      jsonb_build_object(
        'channel', 'repo_docs',
        'factType', 'product_name_alias',
        'sourceFile', 'docs/rules/鋼材規則.txt',
        'locator', 'c_type_default_galvanized_alias'
      )
    )
  ),
  (
    'C鋼',
    '錏輕型鋼',
    'c_type',
    60,
    'reviewed',
    jsonb_build_array(
      jsonb_build_object(
        'channel', 'repo_docs',
        'factType', 'product_name_alias',
        'sourceFile', 'docs/rules/鋼材規則.txt',
        'locator', 'c_type_default_galvanized_alias'
      )
    )
  ),
  (
    '輕型鋼',
    '錏輕型鋼',
    'c_type',
    70,
    'reviewed',
    jsonb_build_array(
      jsonb_build_object(
        'channel', 'repo_docs',
        'factType', 'product_name_alias',
        'sourceFile', 'docs/rules/鋼材規則.txt',
        'locator', 'c_type_default_galvanized_alias'
      )
    )
  )
ON CONFLICT DO NOTHING;

DROP TRIGGER IF EXISTS set_updated_at ON steel.product_name_aliases;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.product_name_aliases
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();
