BEGIN;

CREATE TABLE IF NOT EXISTS steel.instruction_packets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  version INTEGER NOT NULL,
  title TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'zh-TW',
  packet_groups TEXT[] NOT NULL DEFAULT '{}'::text[],
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  instruction TEXT NOT NULL,
  blocking_rules TEXT[] NOT NULL DEFAULT '{}'::text[],
  required_lookups TEXT[] NOT NULL DEFAULT '{}'::text[],
  user_visible_notes TEXT[] NOT NULL DEFAULT '{}'::text[],
  confirmation_questions TEXT[] NOT NULL DEFAULT '{}'::text[],
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'medium',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_packet_id BIGINT REFERENCES steel.instruction_packets(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT instruction_packets_slug_version_unique UNIQUE (slug, version),
  CONSTRAINT instruction_packets_version_check CHECK (version > 0),
  CONSTRAINT instruction_packets_locale_check CHECK (locale <> ''),
  CONSTRAINT instruction_packets_packet_groups_check CHECK (cardinality(packet_groups) > 0),
  CONSTRAINT instruction_packets_selectors_check CHECK (jsonb_typeof(selectors) = 'object'),
  CONSTRAINT instruction_packets_priority_check CHECK (priority >= 0),
  CONSTRAINT instruction_packets_confidence_check CHECK (
    confidence IN ('low', 'medium', 'high')
  ),
  CONSTRAINT instruction_packets_source_refs_check CHECK (
    jsonb_typeof(source_refs) = 'array'
  ),
  CONSTRAINT instruction_packets_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT instruction_packets_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT instruction_packets_no_self_supersede_check CHECK (
    supersedes_packet_id IS NULL OR supersedes_packet_id <> id
  )
);

CREATE INDEX IF NOT EXISTS instruction_packets_review_active_idx
ON steel.instruction_packets (review_state, active);

CREATE INDEX IF NOT EXISTS instruction_packets_packet_groups_idx
ON steel.instruction_packets USING GIN (packet_groups);

CREATE INDEX IF NOT EXISTS instruction_packets_selectors_idx
ON steel.instruction_packets USING GIN (selectors);

CREATE INDEX IF NOT EXISTS instruction_packets_priority_idx
ON steel.instruction_packets (priority, id);

CREATE INDEX IF NOT EXISTS instruction_packets_supersedes_idx
ON steel.instruction_packets (supersedes_packet_id);

DROP TRIGGER IF EXISTS set_updated_at ON steel.instruction_packets;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.instruction_packets
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

INSERT INTO steel.instruction_packets (
  slug,
  version,
  title,
  locale,
  packet_groups,
  selectors,
  instruction,
  blocking_rules,
  required_lookups,
  user_visible_notes,
  confirmation_questions,
  priority,
  confidence,
  source_refs,
  active,
  review_state,
  created_by,
  reviewed_by,
  reviewed_at
)
VALUES
  (
    'angle-surface-oral-zh-v1',
    1,
    '角鐵口語與表面處理候選',
    'zh-TW',
    ARRAY['angle-zinc-quote-core']::text[],
    '{"taskTypes":["quote","price_lookup"],"catalogFamilies":["angle"],"surfaceCandidates":["zinc","galvanized","black"]}'::jsonb,
    'L30x30 可作為等邊角鐵候選；亞只能作低信心表面處理線索，可能代表錏、鍍鋅或相關客戶錯字。查價格前必須產生錏角鐵、錏成型角鐵、鍍鋅角鐵、角鐵與 L30x30 等 candidate queries，並用 reviewed price rows 驗證。成型角鐵若出現 30*2.5*6M 這類價格表規格，除了 30x30 等等邊候選，也必須查 30x2.5x6M、30x2.5 等價格表 spec fragments。',
    ARRAY[
      '不要把 亞L30x30 當作價格表 canonical key。',
      '不要只列最高相似候選，省略其他 bounded options。'
    ]::text[],
    ARRAY['search_price_candidates']::text[],
    ARRAY[
      '亞L30x30 是低信心口語線索；需要列出錏角鐵、錏成型角鐵、鍍鋅角鐵、角鐵等 bounded options。'
    ]::text[],
    ARRAY[
      '請確認 亞 是指錏材、鍍鋅，還是其他表面處理。'
    ]::text[],
    40,
    'medium',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"angle-surface-oral-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'c-type-basic-quote-zh-v1',
    1,
    'C 型鋼專用計價規則',
    'zh-TW',
    ARRAY['c-type-quote-core']::text[],
    '{"taskTypes":["quote","price_lookup"],"catalogFamilies":["c_type"],"formulaCodes":["C"],"processingTypes":["cutting","hole"]}'::jsonb,
    'C 型鋼仍必須先查 reviewed product-price rows，不可只用重量推價。C 型鋼口語品名通常對應產品價格列的輕型鋼品名；例如 C型鋼 100x50x20 2.3t 應以 catalogFamilies: [c_type] 搭配 100x2.3 等尺寸/厚度片段查價。材質不明時，AI 可以先塞 productName: 錏輕型鋼 作為通常情況的高信心候選，同時列出白鐵輕型鋼、黑鐵輕型鋼等 bounded alternatives 並請確認。C 型鋼切工與孔費預設免費，可列為 true-zero/no-charge；這不代表材料單價、特殊加工或非 C 型鋼加工免費。',
    ARRAY[
      '不要把 C型鋼 當作 productName filter 卡死價格查詢；已選 c_type 時，優先用尺寸/厚度 spec fragments 查 reviewed price rows。',
      '不要把 C 型鋼切工/孔費免費規則套用到材料單價、特殊加工或非 C 型鋼品項。',
      '不要把 C 型鋼套用一般長條料 6M 配料、餘料與一般切工邏輯。'
    ]::text[],
    ARRAY['search_price_candidates','lookup_formula','lookup_defaults']::text[],
    ARRAY[
      'C 型鋼材質不明時可先用 productName: 錏輕型鋼 作高信心候選，但要同時列白鐵輕型鋼、黑鐵輕型鋼等 bounded options。',
      'C 型鋼切工與孔費預設免費只適用 C 型鋼一般情境，不代表材料或特殊加工免費。'
    ]::text[],
    ARRAY[
      '請確認 C 型鋼材質是否為錏輕型鋼；若不是，請選白鐵輕型鋼、黑鐵輕型鋼或其他材質。'
    ]::text[],
    40,
    'high',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"c-type-basic-quote-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'price-source-priority-zh-v1',
    1,
    '價格來源優先順序',
    'zh-TW',
    ARRAY['global-quote-core','c-type-quote-core']::text[],
    '{"taskTypes":["quote","price_lookup"],"catalogFamilies":["*"]}'::jsonb,
    '除非使用者明確提供單價，材料與加工報價必須先查 reviewed product-price rows，再依客戶分級與該列計價單位取價。單價空白或 0 預設是 missing price，不可填 0。',
    ARRAY[
      '不要只用手冊重量推價。',
      '不要把 blank / 0 product price 當作免費或 true-zero。'
    ]::text[],
    ARRAY['search_price_candidates']::text[],
    ARRAY[
      '材料與加工價格以 reviewed price rows 優先；空白或 0 不等於免費。'
    ]::text[],
    ARRAY[]::text[],
    50,
    'high',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"price-source-priority-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'h-type-length-surcharge-zh-v1',
    1,
    'H 型鋼米數與非常規加價',
    'zh-TW',
    ARRAY['h-type-quote-core']::text[],
    '{"taskTypes":["quote","price_lookup"],"catalogFamilies":["h_beam"],"lengthMeters":{"regular":[6,9,10,12],"nonRegular":[7,8,11,13,14,15]}}'::jsonb,
    'H 型鋼常規米數為 6M、9M、10M、12M。H 型鋼非常規米數為 7M、8M、11M、13M、14M、15M；非常規米數理論上比一般米數材料 kg 單價 +0.3 元/kg，但產品價格表的 exact reviewed 非常規米數列已含非常規 +0.3 元/kg，查到 7M、8M、11M、13M、14M、15M exact reviewed price row 時不可再加一次。只有缺 exact reviewed 非常規米數價格列、需要從常規米數 kg 單價推估時，才可把 +0.3 元/kg 當 provisional/default derivation，並要求使用者確認。此加價調整材料 kg 單價，不代表切工免費或切工已含；H 型鋼總重仍依 reviewed formula / weight data 計算，切工費要依切工 packet 或 reviewed cutting rows 另算。長度不在常規或非常規列表時，必須標 low confidence 並請使用者確認。',
    ARRAY[
      '不要把非常規 +0.3/kg 套到非 H 型鋼。',
      '不要因非常規加價而省略切工判斷。',
      '查到 exact reviewed 非常規米數價格列時，不可再加 +0.3/kg。'
    ]::text[],
    ARRAY['search_price_candidates','lookup_formula','lookup_defaults']::text[],
    ARRAY[
      'H 型鋼 7M、8M、11M、13M、14M、15M 若查到 exact reviewed 價格列，價格表已含非常規 +0.3/kg，不要再加一次。',
      '若缺 exact reviewed 非常規米數列，只能暫估從常規米數 +0.3/kg，並要求確認。'
    ]::text[],
    ARRAY[
      '請確認 H 型鋼長度是否為 6M、9M、10M、12M 常規米數，或 7M、8M、11M、13M、14M、15M 非常規米數。'
    ]::text[],
    40,
    'high',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"h-type-length-surcharge-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'h-and-i-beam-cutting-price-zh-v1',
    1,
    'H 型鋼與工字鐵切工價錢判讀',
    'zh-TW',
    ARRAY['h-type-quote-core']::text[],
    '{"taskTypes":["quote","processing"],"catalogFamilies":["h_beam","i_beam"],"processingTypes":["cutting","slotting","hole","chamfer"]}'::jsonb,
    'H 型鋼切工優先查 reviewed cutting rows。H 型鋼切工表依尺寸與客戶分級欄位 A/C/F、B 取價；未確認價格不能填 0，必須回 missing / manual review 或相近候選。工字鐵切工參考表可作 i-beam / beam candidate；若用於 H 型鋼，來源備註指出 H 依大小另 +30~50，必須標示需 backend validation / manual review，不能直接硬套。H 14m/m 以上的開槽、沖孔、倒角另計；整理列提供 processing price candidates：開槽 KZZB10 140/150、沖孔 KZZB11 16/17、倒角 KZZB12 140/150。需要這些加工時，先用 search_price_candidates 查 reviewed processing price rows，例如 productName: 開槽加工、沖孔加工、倒角加工 或 specKeyContains: KZZB10/KZZB11/KZZB12，再標示仍需確認加工數量、路徑、孔數與是否適用 H 型鋼厚度。斜切、修頭尾、特別加工需另外判斷切工次數或加價。',
    ARRAY[
      '不要把未確認切工價填 0。',
      '不要把工字鐵切工參考表直接當成 H 型鋼 confirmed price。',
      '不要忽略斜切、修頭尾、特別加工造成的切工次數或加價。'
    ]::text[],
    ARRAY['lookup_defaults','search_price_candidates']::text[],
    ARRAY[
      'H 型鋼切工、開槽、沖孔、倒角要查 reviewed cutting/processing rows；未確認不能填 0。'
    ]::text[],
    ARRAY[
      '請確認 H 型鋼加工數量、孔數、開槽路徑、倒角或斜切是否適用。'
    ]::text[],
    50,
    'medium',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"h-and-i-beam-cutting-price-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'formula-code-selection-zh-v1',
    1,
    '公式編號候選選擇',
    'zh-TW',
    ARRAY['global-quote-core','c-type-quote-core']::text[],
    '{"taskTypes":["quote","formula"],"catalogFamilies":["c_type"],"formulaCodes":["C"]}'::jsonb,
    'C 型鋼候選公式為 C；必須透過 lookup_formula 查 reviewed active formula rows，不可在 prompt 內直接以試算表文字作最終公式來源。',
    ARRAY['不要跳過 lookup_formula 或 reviewed formula validation。']::text[],
    ARRAY['lookup_formula']::text[],
    ARRAY[
      '公式必須查 reviewed formula rows，不可只靠 prompt 內記憶。'
    ]::text[],
    ARRAY[]::text[],
    60,
    'high',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"formula-code-selection-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'drawing-processing-detection-zh-v1',
    1,
    '圖面孔洞與加工判讀',
    'zh-TW',
    ARRAY['plate-processing-core','c-type-quote-core']::text[],
    '{"taskTypes":["quote","drawing","processing"],"processingTypes":["hole","slotting","bending"],"catalogFamilies":["plate","c_type"]}'::jsonb,
    '【孔洞】孔數依表格孔數優先、圖面孔位交叉確認。4-Ø22 = 每片 4 孔。若產品價格.xlsx 有明確沖孔加工品項，優先用該品項。C 型鋼孔費預設免費。',
    ARRAY[
      '不要只依 OCR 算孔洞、開槽、折工。',
      '不要因路徑或刀數不明就填 0；應列人工複核或請使用者確認。'
    ]::text[],
    ARRAY['search_price_candidates','lookup_defaults']::text[],
    ARRAY[
      '孔洞、開槽、折工要依表格和圖面交叉確認；路徑或刀數不明時需要人工複核。'
    ]::text[],
    ARRAY[
      '請確認孔洞數、開槽路徑、折工刀數與每片/每支適用數量。'
    ]::text[],
    70,
    'high',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"drawing-processing-detection-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'oral-material-candidate-generation-zh-v1',
    1,
    '口語品名候選推導',
    'zh-TW',
    ARRAY['global-quote-core','angle-zinc-quote-core']::text[],
    '{"taskTypes":["quote","price_lookup"],"catalogFamilies":["*"]}'::jsonb,
    '客戶口語品名要先拆成材料類別、材質/表面、尺寸、厚度、長度、數量與加工註記。口語轉換只能作為候選，不代表完全匹配；厚度、材質、長度、單位或表面處理不明時，必須降低信心並列出確認選項。',
    ARRAY[
      '不要把口語轉換當作 confirmed source fact。',
      '不要只產生單一最高相似候選；有多個合理 reviewed candidates 時必須列出 bounded options。'
    ]::text[],
    ARRAY['search_price_candidates']::text[],
    ARRAY[
      '口語品名只能作為候選；材質、長度、單位或表面不明時要列 bounded options。'
    ]::text[],
    ARRAY[
      '請確認口語品名對應的材質、表面處理、尺寸、厚度、長度與單位。'
    ]::text[],
    50,
    'medium',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"oral-material-candidate-generation-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'black-steel-cutting-price-zh-v1',
    1,
    '黑鐵類切工候選',
    'zh-TW',
    ARRAY['black-long-material-cutting-core','angle-zinc-quote-core']::text[],
    '{"taskTypes":["quote","processing"],"processingTypes":["cutting"],"catalogFamilies":["black_long_material","angle"]}'::jsonb,
    '黑角鐵、黑槽鐵、黑平鐵、黑鐵管等長條材料需要切工時，應依 reviewed cutting/default data 判斷切工候選與加價；材質、表面處理、厚料、斜切或量少不明時必須標低信心並請確認。',
    ARRAY['不要將黑鐵類切工價自動套到白鐵、錏材或厚料而不加價/不另計。']::text[],
    ARRAY['lookup_defaults']::text[],
    ARRAY[
      '黑鐵類切工需要依 reviewed cutting/default data；厚料、斜切或量少要確認。'
    ]::text[],
    ARRAY[
      '請確認切工是否為黑鐵長條材料、是否有厚料、斜切或量少加價。'
    ]::text[],
    60,
    'medium',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"black-steel-cutting-price-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  ),
  (
    'cut-count-and-trim-detection-zh-v1',
    1,
    '切刀數與修頭尾判讀',
    'zh-TW',
    ARRAY['h-type-quote-core','black-long-material-cutting-core','angle-zinc-quote-core']::text[],
    '{"taskTypes":["quote","processing"],"processingTypes":["cutting","head_tail_trim","angle_cut"]}'::jsonb,
    '一個切口預設為 1 刀；修頭尾時需把頭修、中間切、尾修分開判斷。斜切、翼板切斜、特殊角度或手寫不清時，必須列 low confidence 或 manual review。',
    ARRAY['不要把「修頭尾」算成 1 刀。']::text[],
    ARRAY['lookup_defaults']::text[],
    ARRAY[
      '一個切口預設 1 刀；修頭尾要分開算，不能直接算成 1 刀。'
    ]::text[],
    ARRAY[
      '請確認是否有修頭尾、斜切、翼板切斜或特殊角度。'
    ]::text[],
    60,
    'medium',
    '[{"channel":"repo_docs","factType":"instruction_packet","sourceFile":"tasks/steel-data-rules-architecture/instruction-packets.md","locator":"cut-count-and-trim-detection-zh-v1"}]'::jsonb,
    true,
    'reviewed',
    'migration:steel_instruction_packets',
    'migration:steel_instruction_packets',
    NOW()
  )
ON CONFLICT (slug, version) DO UPDATE SET
  title = EXCLUDED.title,
  locale = EXCLUDED.locale,
  packet_groups = EXCLUDED.packet_groups,
  selectors = EXCLUDED.selectors,
  instruction = EXCLUDED.instruction,
  blocking_rules = EXCLUDED.blocking_rules,
  required_lookups = EXCLUDED.required_lookups,
  user_visible_notes = EXCLUDED.user_visible_notes,
  confirmation_questions = EXCLUDED.confirmation_questions,
  priority = EXCLUDED.priority,
  confidence = EXCLUDED.confidence,
  source_refs = EXCLUDED.source_refs,
  active = EXCLUDED.active,
  review_state = EXCLUDED.review_state,
  reviewed_by = EXCLUDED.reviewed_by,
  reviewed_at = EXCLUDED.reviewed_at,
  updated_at = NOW();

REVOKE ALL ON TABLE steel.instruction_packets FROM anon, authenticated;
REVOKE ALL ON SEQUENCE steel.instruction_packets_id_seq FROM anon, authenticated;

COMMIT;
