BEGIN;

SET search_path = steel, public;

CREATE TABLE IF NOT EXISTS steel.calculation_rule_defaults (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  scope_type TEXT NOT NULL DEFAULT 'company',
  customer_id BIGINT REFERENCES steel.customers(id),
  customer_tier_id BIGINT REFERENCES steel.customer_tiers(id),
  material_family TEXT,
  product_family TEXT,
  charge_type TEXT NOT NULL,
  formula_code TEXT NOT NULL,
  formula_version_id BIGINT REFERENCES steel.formula_versions(id),
  selector JSONB NOT NULL DEFAULT '{}'::jsonb,
  effect TEXT NOT NULL DEFAULT 'calculation_default',
  default_parameters JSONB NOT NULL DEFAULT '[]'::jsonb,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'high',
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT calculation_rule_defaults_code_unique UNIQUE (code),
  CONSTRAINT calculation_rule_defaults_scope_type_check CHECK (
    scope_type IN ('customer', 'customer_tier', 'material_family', 'product_family', 'company')
  ),
  CONSTRAINT calculation_rule_defaults_scope_required_check CHECK (
    (scope_type = 'customer' AND customer_id IS NOT NULL)
    OR (scope_type = 'customer_tier' AND customer_tier_id IS NOT NULL)
    OR (scope_type = 'material_family' AND material_family IS NOT NULL)
    OR (scope_type = 'product_family' AND product_family IS NOT NULL)
    OR scope_type = 'company'
  ),
  CONSTRAINT calculation_rule_defaults_charge_type_check CHECK (
    charge_type IN ('material', 'cutting', 'hole', 'slotting', 'bending', 'processing')
  ),
  CONSTRAINT calculation_rule_defaults_selector_check CHECK (
    jsonb_typeof(selector) = 'object'
  ),
  CONSTRAINT calculation_rule_defaults_effect_check CHECK (
    effect IN (
      'calculation_default',
      'material_rule',
      'preference_rule',
      'formula_hint',
      'true_zero_rule',
      'skip_charge',
      'parameter_override'
    )
  ),
  CONSTRAINT calculation_rule_defaults_parameters_check CHECK (
    jsonb_typeof(default_parameters) = 'array'
  ),
  CONSTRAINT calculation_rule_defaults_priority_check CHECK (priority >= 0),
  CONSTRAINT calculation_rule_defaults_confidence_check CHECK (
    confidence IN ('low', 'medium', 'high')
  ),
  CONSTRAINT calculation_rule_defaults_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT calculation_rule_defaults_source_refs_check CHECK (
    jsonb_typeof(source_refs) = 'array'
  )
);

CREATE INDEX IF NOT EXISTS calculation_rule_defaults_review_active_idx
ON steel.calculation_rule_defaults (review_state, active);

CREATE INDEX IF NOT EXISTS calculation_rule_defaults_customer_lookup_idx
ON steel.calculation_rule_defaults (
  customer_id,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS calculation_rule_defaults_tier_lookup_idx
ON steel.calculation_rule_defaults (
  customer_tier_id,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS calculation_rule_defaults_material_lookup_idx
ON steel.calculation_rule_defaults (
  material_family,
  product_family,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS calculation_rule_defaults_formula_idx
ON steel.calculation_rule_defaults (formula_code, formula_version_id);

CREATE TABLE IF NOT EXISTS steel.lesson_memory_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_type TEXT NOT NULL,
  origin_table TEXT NOT NULL,
  origin_id TEXT NOT NULL,
  origin_revision TEXT,
  scope_type TEXT NOT NULL,
  customer_id BIGINT REFERENCES steel.customers(id),
  customer_tier_id BIGINT REFERENCES steel.customer_tiers(id),
  material_family TEXT,
  product_family TEXT,
  charge_type TEXT,
  formula_code TEXT,
  selector JSONB NOT NULL DEFAULT '{}'::jsonb,
  effect TEXT NOT NULL,
  default_parameters JSONB NOT NULL DEFAULT '[]'::jsonb,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'high',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_entry_id BIGINT REFERENCES steel.lesson_memory_entries(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT lesson_memory_entries_entry_type_check CHECK (
    entry_type IN (
      'calculation_default',
      'material_rule',
      'preference_rule',
      'formula_hint',
      'true_zero_rule'
    )
  ),
  CONSTRAINT lesson_memory_entries_scope_type_check CHECK (
    scope_type IN ('customer', 'customer_tier', 'material_family', 'product_family', 'company')
  ),
  CONSTRAINT lesson_memory_entries_scope_required_check CHECK (
    (scope_type = 'customer' AND customer_id IS NOT NULL)
    OR (scope_type = 'customer_tier' AND customer_tier_id IS NOT NULL)
    OR (scope_type = 'material_family' AND material_family IS NOT NULL)
    OR (scope_type = 'product_family' AND product_family IS NOT NULL)
    OR scope_type = 'company'
  ),
  CONSTRAINT lesson_memory_entries_charge_type_check CHECK (
    charge_type IS NULL
    OR charge_type IN ('material', 'cutting', 'hole', 'slotting', 'bending', 'processing')
  ),
  CONSTRAINT lesson_memory_entries_selector_check CHECK (
    jsonb_typeof(selector) = 'object'
  ),
  CONSTRAINT lesson_memory_entries_effect_check CHECK (
    effect IN (
      'calculation_default',
      'material_rule',
      'preference_rule',
      'formula_hint',
      'true_zero_rule',
      'skip_charge',
      'parameter_override'
    )
  ),
  CONSTRAINT lesson_memory_entries_parameters_check CHECK (
    jsonb_typeof(default_parameters) = 'array'
  ),
  CONSTRAINT lesson_memory_entries_priority_check CHECK (priority >= 0),
  CONSTRAINT lesson_memory_entries_confidence_check CHECK (
    confidence IN ('low', 'medium', 'high')
  ),
  CONSTRAINT lesson_memory_entries_source_refs_check CHECK (
    jsonb_typeof(source_refs) = 'array'
  ),
  CONSTRAINT lesson_memory_entries_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT lesson_memory_entries_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT lesson_memory_entries_no_self_supersede_check CHECK (
    supersedes_entry_id IS NULL OR supersedes_entry_id <> id
  )
);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_review_active_idx
ON steel.lesson_memory_entries (review_state, active);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_customer_lookup_idx
ON steel.lesson_memory_entries (
  customer_id,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_tier_lookup_idx
ON steel.lesson_memory_entries (
  customer_tier_id,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_material_lookup_idx
ON steel.lesson_memory_entries (
  material_family,
  product_family,
  charge_type,
  formula_code,
  active,
  priority
);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_origin_idx
ON steel.lesson_memory_entries (origin_table, origin_id, origin_revision);

CREATE INDEX IF NOT EXISTS lesson_memory_entries_supersedes_idx
ON steel.lesson_memory_entries (supersedes_entry_id);

DROP TRIGGER IF EXISTS set_updated_at ON steel.calculation_rule_defaults;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.calculation_rule_defaults
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON steel.lesson_memory_entries;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.lesson_memory_entries
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

REVOKE ALL ON TABLE steel.calculation_rule_defaults FROM anon, authenticated;
REVOKE ALL ON TABLE steel.lesson_memory_entries FROM anon, authenticated;
REVOKE ALL ON SEQUENCE steel.calculation_rule_defaults_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE steel.lesson_memory_entries_id_seq FROM anon, authenticated;

COMMIT;
