ALTER TABLE steel.prices
  DROP CONSTRAINT IF EXISTS prices_category_check,
  DROP CONSTRAINT IF EXISTS prices_material_check,
  DROP CONSTRAINT IF EXISTS prices_value_state_check,
  DROP CONSTRAINT IF EXISTS prices_unit_prices_nonnegative_check,
  DROP CONSTRAINT IF EXISTS prices_confirmed_has_price_check,
  DROP CONSTRAINT IF EXISTS prices_unknown_has_no_price_check;

ALTER TABLE steel.prices
  ALTER COLUMN product_name DROP NOT NULL,
  ALTER COLUMN unit DROP NOT NULL,
  ALTER COLUMN unit DROP DEFAULT,
  ALTER COLUMN unit_price_a TYPE NUMERIC(18, 4) USING unit_price_a::NUMERIC(18, 4),
  ALTER COLUMN unit_price_b TYPE NUMERIC(18, 4) USING unit_price_b::NUMERIC(18, 4),
  ALTER COLUMN unit_price_c TYPE NUMERIC(18, 4) USING unit_price_c::NUMERIC(18, 4),
  ALTER COLUMN unit_price_f TYPE NUMERIC(18, 4) USING unit_price_f::NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS formula_code TEXT,
  ADD COLUMN IF NOT EXISTS normalized_spec_text TEXT,
  ADD COLUMN IF NOT EXISTS dimension_signature TEXT,
  ADD COLUMN IF NOT EXISTS unit_price_base NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS unit_price_d NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS unit_price_e NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_a NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_b NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_c NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_d NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_e NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS price_ratio_f NUMERIC(18, 4),
  ADD COLUMN IF NOT EXISTS unit_weight_value NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS unit_weight_basis TEXT,
  ADD COLUMN IF NOT EXISTS density NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS width_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS height_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS length_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS outer_diameter_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS nominal_inch TEXT,
  ADD COLUMN IF NOT EXISTS web_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS flange_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS lip_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS sheet_width_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS sheet_length_mm NUMERIC(18, 6),
  ADD COLUMN IF NOT EXISTS spec_sort_key TEXT,
  ADD COLUMN IF NOT EXISTS cost_basis TEXT;
