BEGIN;

SET search_path = steel, public;

DROP INDEX IF EXISTS steel.catalog_families_inference_rules_idx;

ALTER TABLE steel.catalog_families
  DROP CONSTRAINT IF EXISTS catalog_families_inference_rules_check,
  DROP COLUMN IF EXISTS inference_rules;

DROP INDEX IF EXISTS steel.quote_defaults_product_name_lookup_idx;

ALTER TABLE steel.quote_defaults
  DROP CONSTRAINT IF EXISTS quote_defaults_default_type_check,
  DROP CONSTRAINT IF EXISTS quote_defaults_scope_type_check,
  DROP CONSTRAINT IF EXISTS quote_defaults_scope_required_check,
  DROP CONSTRAINT IF EXISTS quote_defaults_effect_check,
  DROP CONSTRAINT IF EXISTS quote_defaults_product_name_not_blank_check,
  DROP COLUMN IF EXISTS product_name;

ALTER TABLE steel.quote_defaults
  ADD CONSTRAINT quote_defaults_default_type_check CHECK (
    default_type IN (
      'calculation_default',
      'material_rule',
      'preference_rule',
      'formula_hint',
      'true_zero_rule'
    )
  ),
  ADD CONSTRAINT quote_defaults_scope_type_check CHECK (
    scope_type IN ('customer', 'customer_tier', 'catalog_family', 'product_family', 'company')
  ),
  ADD CONSTRAINT quote_defaults_scope_required_check CHECK (
    (scope_type = 'customer' AND customer_id IS NOT NULL)
    OR (scope_type = 'customer_tier' AND customer_tier_id IS NOT NULL)
    OR (scope_type = 'catalog_family' AND catalog_family IS NOT NULL)
    OR (scope_type = 'product_family' AND product_family IS NOT NULL)
    OR scope_type = 'company'
  ),
  ADD CONSTRAINT quote_defaults_effect_check CHECK (
    effect IN (
      'calculation_default',
      'material_rule',
      'preference_rule',
      'formula_hint',
      'true_zero_rule',
      'skip_charge',
      'parameter_override'
    )
  );

CREATE TABLE IF NOT EXISTS steel.agent_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  version INTEGER NOT NULL,
  rule_type TEXT NOT NULL,
  title TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'zh-TW',
  rule_sections TEXT[] NOT NULL DEFAULT '{}'::text[],
  sheet_id TEXT,
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  prompt TEXT NOT NULL,
  tool_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'high',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_rule_id BIGINT REFERENCES steel.agent_rules(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT agent_rules_slug_version_unique UNIQUE (slug, version),
  CONSTRAINT agent_rules_slug_not_blank_check CHECK (btrim(slug) <> ''),
  CONSTRAINT agent_rules_version_check CHECK (version > 0),
  CONSTRAINT agent_rules_type_check CHECK (
    rule_type IN (
      'agent_instruction_rule',
      'tool_flow_rule',
      'inference_order_rule',
      'output_policy_rule',
      'workbook_output_rule'
    )
  ),
  CONSTRAINT agent_rules_title_not_blank_check CHECK (btrim(title) <> ''),
  CONSTRAINT agent_rules_locale_not_blank_check CHECK (btrim(locale) <> ''),
  CONSTRAINT agent_rules_sections_check CHECK (cardinality(rule_sections) > 0),
  CONSTRAINT agent_rules_sheet_id_not_blank_check CHECK (
    sheet_id IS NULL OR btrim(sheet_id) <> ''
  ),
  CONSTRAINT agent_rules_selectors_check CHECK (jsonb_typeof(selectors) = 'object'),
  CONSTRAINT agent_rules_prompt_not_blank_check CHECK (btrim(prompt) <> ''),
  CONSTRAINT agent_rules_tool_policy_check CHECK (jsonb_typeof(tool_policy) = 'object'),
  CONSTRAINT agent_rules_output_policy_check CHECK (jsonb_typeof(output_policy) = 'object'),
  CONSTRAINT agent_rules_priority_check CHECK (priority >= 0),
  CONSTRAINT agent_rules_confidence_check CHECK (confidence IN ('low', 'medium', 'high')),
  CONSTRAINT agent_rules_source_refs_check CHECK (jsonb_typeof(source_refs) = 'array'),
  CONSTRAINT agent_rules_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT agent_rules_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT agent_rules_no_self_supersede_check CHECK (
    supersedes_rule_id IS NULL OR supersedes_rule_id <> id
  )
);

CREATE INDEX IF NOT EXISTS agent_rules_review_active_idx
ON steel.agent_rules (review_state, active, priority, id);

CREATE INDEX IF NOT EXISTS agent_rules_sections_idx
ON steel.agent_rules USING GIN (rule_sections);

CREATE INDEX IF NOT EXISTS agent_rules_sheet_lookup_idx
ON steel.agent_rules (sheet_id, active, priority, id);

CREATE INDEX IF NOT EXISTS agent_rules_selectors_idx
ON steel.agent_rules USING GIN (selectors);

CREATE INDEX IF NOT EXISTS agent_rules_tool_policy_idx
ON steel.agent_rules USING GIN (tool_policy);

CREATE INDEX IF NOT EXISTS agent_rules_supersedes_idx
ON steel.agent_rules (supersedes_rule_id);

CREATE TABLE IF NOT EXISTS steel.catalog_family_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type TEXT NOT NULL,
  catalog_family TEXT REFERENCES steel.catalog_families(key),
  product_name TEXT,
  product_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  prompt TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'medium',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_rule_id BIGINT REFERENCES steel.catalog_family_rules(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT catalog_family_rules_type_check CHECK (
    rule_type IN (
      'catalog_family_rule',
      'catalog_family_inference_rule',
      'product_name_rule',
      'product_alias_rule',
      'similar_product_name_rule'
    )
  ),
  CONSTRAINT catalog_family_rules_scope_check CHECK (
    catalog_family IS NOT NULL
    OR product_name IS NOT NULL
    OR jsonb_array_length(product_names) > 0
    OR jsonb_array_length(aliases) > 0
  ),
  CONSTRAINT catalog_family_rules_product_name_not_blank_check CHECK (
    product_name IS NULL OR btrim(product_name) <> ''
  ),
  CONSTRAINT catalog_family_rules_product_names_check CHECK (
    jsonb_typeof(product_names) = 'array'
  ),
  CONSTRAINT catalog_family_rules_aliases_check CHECK (jsonb_typeof(aliases) = 'array'),
  CONSTRAINT catalog_family_rules_selectors_check CHECK (jsonb_typeof(selectors) = 'object'),
  CONSTRAINT catalog_family_rules_prompt_not_blank_check CHECK (btrim(prompt) <> ''),
  CONSTRAINT catalog_family_rules_priority_check CHECK (priority >= 0),
  CONSTRAINT catalog_family_rules_confidence_check CHECK (confidence IN ('low', 'medium', 'high')),
  CONSTRAINT catalog_family_rules_source_refs_check CHECK (jsonb_typeof(source_refs) = 'array'),
  CONSTRAINT catalog_family_rules_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT catalog_family_rules_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT catalog_family_rules_no_self_supersede_check CHECK (
    supersedes_rule_id IS NULL OR supersedes_rule_id <> id
  )
);

CREATE INDEX IF NOT EXISTS catalog_family_rules_review_active_idx
ON steel.catalog_family_rules (review_state, active, priority, id);

CREATE INDEX IF NOT EXISTS catalog_family_rules_family_lookup_idx
ON steel.catalog_family_rules (catalog_family, active, priority, id);

CREATE INDEX IF NOT EXISTS catalog_family_rules_product_name_lookup_idx
ON steel.catalog_family_rules (lower(product_name), active, priority, id);

CREATE INDEX IF NOT EXISTS catalog_family_rules_product_names_idx
ON steel.catalog_family_rules USING GIN (product_names);

CREATE INDEX IF NOT EXISTS catalog_family_rules_aliases_idx
ON steel.catalog_family_rules USING GIN (aliases);

CREATE INDEX IF NOT EXISTS catalog_family_rules_selectors_idx
ON steel.catalog_family_rules USING GIN (selectors);

CREATE INDEX IF NOT EXISTS catalog_family_rules_supersedes_idx
ON steel.catalog_family_rules (supersedes_rule_id);

CREATE TABLE IF NOT EXISTS steel.quote_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type TEXT NOT NULL,
  scope_type TEXT NOT NULL DEFAULT 'company',
  catalog_family TEXT REFERENCES steel.catalog_families(key),
  product_family TEXT,
  charge_type TEXT,
  formula_code TEXT,
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  parameters JSONB NOT NULL DEFAULT '[]'::jsonb,
  prompt TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'high',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_rule_id BIGINT REFERENCES steel.quote_rules(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quote_rules_type_check CHECK (
    rule_type IN (
      'catalog_decision_rule',
      'order_format_rule',
      'calculation_rule',
      'pricing_rule',
      'material_rule',
      'preference_rule',
      'formula_hint_rule',
      'true_zero_rule',
      'skip_charge_rule',
      'parameter_override_rule'
    )
  ),
  CONSTRAINT quote_rules_scope_type_check CHECK (
    scope_type IN ('catalog_family', 'product_family', 'company')
  ),
  CONSTRAINT quote_rules_scope_required_check CHECK (
    (scope_type = 'catalog_family' AND catalog_family IS NOT NULL)
    OR (scope_type = 'product_family' AND product_family IS NOT NULL)
    OR scope_type = 'company'
  ),
  CONSTRAINT quote_rules_charge_type_check CHECK (
    charge_type IS NULL
    OR charge_type IN ('material', 'cutting', 'hole', 'slotting', 'bending', 'processing')
  ),
  CONSTRAINT quote_rules_selectors_check CHECK (jsonb_typeof(selectors) = 'object'),
  CONSTRAINT quote_rules_parameters_check CHECK (jsonb_typeof(parameters) = 'array'),
  CONSTRAINT quote_rules_prompt_not_blank_check CHECK (btrim(prompt) <> ''),
  CONSTRAINT quote_rules_priority_check CHECK (priority >= 0),
  CONSTRAINT quote_rules_confidence_check CHECK (confidence IN ('low', 'medium', 'high')),
  CONSTRAINT quote_rules_source_refs_check CHECK (jsonb_typeof(source_refs) = 'array'),
  CONSTRAINT quote_rules_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT quote_rules_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT quote_rules_no_self_supersede_check CHECK (
    supersedes_rule_id IS NULL OR supersedes_rule_id <> id
  )
);

CREATE INDEX IF NOT EXISTS quote_rules_review_active_idx
ON steel.quote_rules (review_state, active, priority, id);

CREATE INDEX IF NOT EXISTS quote_rules_catalog_lookup_idx
ON steel.quote_rules (catalog_family, charge_type, formula_code, active, priority, id);

CREATE INDEX IF NOT EXISTS quote_rules_product_family_lookup_idx
ON steel.quote_rules (product_family, charge_type, formula_code, active, priority, id);

CREATE INDEX IF NOT EXISTS quote_rules_selectors_idx
ON steel.quote_rules USING GIN (selectors);

CREATE INDEX IF NOT EXISTS quote_rules_supersedes_idx
ON steel.quote_rules (supersedes_rule_id);

CREATE TABLE IF NOT EXISTS steel.customer_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type TEXT NOT NULL,
  customer_id BIGINT REFERENCES steel.customers(id),
  customer_tier_id BIGINT REFERENCES steel.customer_tiers(id),
  catalog_family TEXT REFERENCES steel.catalog_families(key),
  product_family TEXT,
  charge_type TEXT,
  formula_code TEXT,
  selectors JSONB NOT NULL DEFAULT '{}'::jsonb,
  parameters JSONB NOT NULL DEFAULT '[]'::jsonb,
  prompt TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 100,
  confidence TEXT NOT NULL DEFAULT 'high',
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  review_state TEXT NOT NULL DEFAULT 'reviewed',
  supersedes_rule_id BIGINT REFERENCES steel.customer_rules(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  invalidated_at TIMESTAMPTZ,
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT customer_rules_type_check CHECK (
    rule_type IN (
      'customer_rule',
      'customer_spec_rule',
      'customer_price_rule',
      'customer_default_rule',
      'customer_processing_rule'
    )
  ),
  CONSTRAINT customer_rules_scope_check CHECK (
    customer_id IS NOT NULL OR customer_tier_id IS NOT NULL
  ),
  CONSTRAINT customer_rules_charge_type_check CHECK (
    charge_type IS NULL
    OR charge_type IN ('material', 'cutting', 'hole', 'slotting', 'bending', 'processing')
  ),
  CONSTRAINT customer_rules_selectors_check CHECK (jsonb_typeof(selectors) = 'object'),
  CONSTRAINT customer_rules_parameters_check CHECK (jsonb_typeof(parameters) = 'array'),
  CONSTRAINT customer_rules_prompt_not_blank_check CHECK (btrim(prompt) <> ''),
  CONSTRAINT customer_rules_priority_check CHECK (priority >= 0),
  CONSTRAINT customer_rules_confidence_check CHECK (confidence IN ('low', 'medium', 'high')),
  CONSTRAINT customer_rules_source_refs_check CHECK (jsonb_typeof(source_refs) = 'array'),
  CONSTRAINT customer_rules_review_state_check CHECK (
    review_state IN ('draft', 'needs_review', 'reviewed', 'rejected')
  ),
  CONSTRAINT customer_rules_invalidated_inactive_check CHECK (
    invalidated_at IS NULL OR active = false
  ),
  CONSTRAINT customer_rules_no_self_supersede_check CHECK (
    supersedes_rule_id IS NULL OR supersedes_rule_id <> id
  )
);

CREATE INDEX IF NOT EXISTS customer_rules_review_active_idx
ON steel.customer_rules (review_state, active, priority, id);

CREATE INDEX IF NOT EXISTS customer_rules_customer_lookup_idx
ON steel.customer_rules (customer_id, catalog_family, charge_type, formula_code, active, priority, id);

CREATE INDEX IF NOT EXISTS customer_rules_tier_lookup_idx
ON steel.customer_rules (customer_tier_id, catalog_family, charge_type, formula_code, active, priority, id);

CREATE INDEX IF NOT EXISTS customer_rules_selectors_idx
ON steel.customer_rules USING GIN (selectors);

CREATE INDEX IF NOT EXISTS customer_rules_supersedes_idx
ON steel.customer_rules (supersedes_rule_id);

COMMENT ON TABLE steel.agent_rules IS
  'Always-on Steel AI process rules, including the default Agent Instruction, tool flow, inference order, output policy, and workbook output flow.';
COMMENT ON COLUMN steel.agent_rules.rule_type IS
  'Process rule kind: agent_instruction_rule, tool_flow_rule, inference_order_rule, output_policy_rule, or workbook_output_rule.';
COMMENT ON COLUMN steel.agent_rules.sheet_id IS
  'Optional workbook sheet scope for workbook_output_rule rows; sheet/column structure remains code-owned.';

COMMENT ON TABLE steel.catalog_family_rules IS
  'Rules for product-name, alias, typo, and catalog-family inference returned through lookup_catalog_families.';
COMMENT ON COLUMN steel.catalog_family_rules.product_names IS
  'Reviewed product-name candidates that AI may use for follow-up price lookup after reasoning, not backend-selected finals.';
COMMENT ON COLUMN steel.catalog_family_rules.aliases IS
  'Reviewed customer wording, aliases, typos, or similar names used as inference hints.';

COMMENT ON TABLE steel.quote_rules IS
  'Rules for catalog/category order-format techniques, specific calculation behavior, and price calculation used through lookup_quote_rules.';
COMMENT ON COLUMN steel.quote_rules.rule_type IS
  'Quote rule kind: catalog_decision_rule, order_format_rule, calculation_rule, pricing_rule, material_rule, preference_rule, formula_hint_rule, true_zero_rule, skip_charge_rule, or parameter_override_rule.';

COMMENT ON TABLE steel.customer_rules IS
  'Customer-specific specification, pricing, default, and processing rules returned with search_customers.';
COMMENT ON COLUMN steel.customer_rules.rule_type IS
  'Customer rule kind: customer_rule, customer_spec_rule, customer_price_rule, customer_default_rule, or customer_processing_rule.';

DROP TRIGGER IF EXISTS set_updated_at ON steel.agent_rules;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.agent_rules
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON steel.catalog_family_rules;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.catalog_family_rules
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON steel.quote_rules;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.quote_rules
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON steel.customer_rules;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON steel.customer_rules
FOR EACH ROW EXECUTE FUNCTION steel.set_updated_at();

REVOKE ALL ON ALL TABLES IN SCHEMA steel FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA steel FROM anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA steel FROM anon, authenticated;

COMMIT;
